# Generated by jiko-bundler. Edit the source files, not this bundle.

import json
import logging
import os
import platform
import re
import sys
import tempfile
import time
import urllib.error
import urllib.request
from abc import ABC, abstractmethod
from contextlib import contextmanager
from dataclasses import dataclass, field
from logging import Logger
from pathlib import Path
from typing import (
    Any,
    Dict,
    Generator,
    Generic,
    List,
    MutableMapping,
    Optional,
    TypeAlias,
    TypedDict,
    TypeVar,
)

import c4d
import maxon

# --- jiko_bridge_client.models ---

# Data models shared by every Jiko Bridge integration.
# Code by Semyon Shapoval, 2026


@dataclass
class AssetFile:
    """Represents a file associated with an asset."""

    filepath: Optional[str] = None
    asset_type: Optional[str] = None
    bridge_type: Optional[str] = None

    @classmethod
    def from_dict(cls, data: dict) -> 'AssetFile':
        """Create an AssetFile instance from a dictionary."""
        return cls(
            filepath=data.get('filepath', None),
            asset_type=data.get('assetType', None),
            bridge_type=data.get('bridgeType', None),
        )

    def to_dict(self) -> dict:
        """Convert the AssetFile instance to a dictionary."""
        result: Dict[str, Any] = {}
        if self.filepath:
            result['filepath'] = self.filepath
        if self.asset_type:
            result['assetType'] = self.asset_type
        if self.bridge_type:
            result['bridgeType'] = self.bridge_type
        return result


@dataclass
class AssetModel:
    """Represents a complete asset with its metadata and associated files."""

    vault_name: Optional[str] = None
    pack_name: Optional[str] = None
    asset_name: Optional[str] = None
    active_type: Optional[str] = None
    files: List[AssetFile] = field(default_factory=list)

    def __hash__(self) -> int:
        return hash((self.vault_name, self.pack_name, self.asset_name))

    @classmethod
    def from_string(cls, value: str) -> Optional['AssetModel']:
        """Parse packName / assetName from a placeholder object/tag name."""
        normalized = re.sub('\\.\\d+$', '', value)
        pattern = re.compile('(?P<pack>.+?)__(?P<asset>.+?)$')
        m = pattern.match(normalized)
        if m:
            return cls(pack_name=m.group('pack'), asset_name=m.group('asset'))
        return None

    @classmethod
    def from_dict(cls, data: dict) -> 'AssetModel':
        """Create an AssetModel instance from a dictionary."""
        return cls(
            vault_name=data.get('vaultName'),
            pack_name=data.get('packName'),
            asset_name=data.get('assetName'),
            files=[AssetFile.from_dict(f) for f in data.get('files', [])],
        )

    def to_dict(self) -> dict:
        """Convert the AssetModel instance to a dictionary."""
        result: Dict[str, Any] = {}
        files = list(self.files)
        if self.active_type:
            files.append(AssetFile(asset_type=self.active_type))
        if self.vault_name:
            result['vaultName'] = self.vault_name
        if self.pack_name:
            result['packName'] = self.pack_name
        if self.asset_name:
            result['assetName'] = self.asset_name
        if files:
            result['files'] = [f.to_dict() for f in files]
        return result


class JbPlaceholderInfo(TypedDict):
    """Represents information about a placeholder object."""

    asset: AssetModel
    transform: Any


# --- jiko_bridge_client.contracts ---

JbSourceT = TypeVar('JbSourceT')
JbMatrixT = TypeVar('JbMatrixT')
JbContainerT = TypeVar('JbContainerT')
JbObjectT = TypeVar('JbObjectT')
JbMaterialT = TypeVar('JbMaterialT')


class JbSceneABC(ABC, Generic[JbSourceT, JbMatrixT, JbContainerT, JbObjectT, JbMaterialT]):
    """Abstract base class for all Jiko Bridge scene operations."""

    @abstractmethod
    def __init__(self, source: JbSourceT): ...

    @property
    @abstractmethod
    def source(self) -> JbSourceT:
        """Return the source scene."""

    @property
    @abstractmethod
    def logger(self) -> Logger:
        """Return the logger instance."""

    @abstractmethod
    def walk(
        self, root: list[JbObjectT | JbContainerT | JbMaterialT]
    ) -> list[JbObjectT | JbContainerT | JbMaterialT]:
        """Call *fn* for every object in the root hierarchy (pre-order)."""

    @abstractmethod
    def get_materials_from_objects(self, objects: list[JbObjectT]) -> list[JbMaterialT]:
        """Return materials used by the given objects."""

    @abstractmethod
    def get_selection(self) -> list[JbObjectT | JbContainerT | JbMaterialT]:
        """Return the currently selected objects or materials."""

    @abstractmethod
    def copy_object_transform(self, obj: JbObjectT, target_obj: JbObjectT) -> None:
        """Set the transform of the given object."""

    @abstractmethod
    def remove_object(self, obj: JbObjectT) -> None:
        """Remove the given object from the scene."""

    @abstractmethod
    def get_depth(self, obj: JbObjectT | JbContainerT | JbMaterialT) -> int:
        """Return the depth of the given object in the hierarchy."""

    @abstractmethod
    def merge_duplicates_materials(self, material: JbMaterialT) -> None:
        """Replace duplicate materials (.001, .002, ...) with the given base material."""

    @abstractmethod
    def get_container(self, asset: AssetModel) -> Optional[JbContainerT]:
        """Get the container associated with the given asset, if it exists."""

    @abstractmethod
    def get_or_create_container(
        self, name: str, parent: Optional[JbContainerT] = None
    ) -> JbContainerT:
        """Get or create a container with the given name under the parent."""

    @abstractmethod
    def get_or_create_asset_container(
        self, asset: AssetModel, file: Optional[AssetFile] = None
    ) -> tuple[JbContainerT, bool]:
        """Get or create a container with asset data."""

    @abstractmethod
    def set_asset_data(
        self, container: JbContainerT, asset: AssetModel, file: Optional[AssetFile] = None
    ) -> None:
        """Store asset info in the container's custom properties."""

    @abstractmethod
    def get_asset_data_from_container(self, container: JbContainerT) -> Optional[AssetModel]:
        """Parse asset info from a container's custom properties."""

    @abstractmethod
    def copy_asset_data(self, src: JbContainerT, dst: JbContainerT | JbObjectT) -> None:
        """Copy custom properties from src to dst."""

    @abstractmethod
    def get_containers_from_objects(self, objects: list[JbObjectT]) -> list[JbContainerT]:
        """Return asset containers found among the given objects (via instance Empties)."""

    @abstractmethod
    def get_containers_from_instances(self, objects: list[JbObjectT]) -> list[JbContainerT]:
        """Return asset containers found among the given instances."""

    @abstractmethod
    def move_objects_to_container(self, objects: list[JbObjectT], container: JbContainerT) -> None:
        """Move objects into target collection."""

    @abstractmethod
    def cleanup_container(self, container: JbContainerT) -> None:
        """Remove empty objects that have no children and no data."""

    @abstractmethod
    def clear_container(self, container: JbContainerT) -> None:
        """Remove all objects from the container."""

    @abstractmethod
    def get_children(self, obj: JbObjectT | JbContainerT) -> list[JbObjectT | JbContainerT]:
        """Return the children of the given object or container."""

    @abstractmethod
    def create_instance(self, container: JbContainerT, name: str) -> JbObjectT:
        """Create an instance of the given object."""

    @abstractmethod
    def get_names_from_placeholder(self, obj: JbObjectT) -> List[str]:
        """Extract placeholder info from objects and remove them."""

    @abstractmethod
    def replace_instances_with_placeholders(
        self, objects: list[JbObjectT], source: JbSourceT
    ) -> list[JbObjectT]:
        """Replace instances in the list with placeholders."""

    @abstractmethod
    def create_placeholder(
        self, asset_model: AssetModel, transform: JbMatrixT, source: JbSourceT
    ) -> JbObjectT:
        """Create a placeholder object in the scene based on the info."""

    @abstractmethod
    def import_file(self, file_path: str) -> bool:
        """Import a file into the active scene."""

    @abstractmethod
    def _import_fbx(self, file_path: str) -> bool: ...

    @abstractmethod
    def export_file(self, ext: str) -> Optional[str]:
        """Export the active scene to a file and return its path."""

    @abstractmethod
    def _export_fbx(self, file_path: str) -> Optional[str]: ...

    @abstractmethod
    def temp_source(
        self,
        objects: Optional[list[JbObjectT | JbContainerT]] = None,
        unit_scale: float | int = 1.0,
        debug: bool = False,
    ) -> Generator[JbSourceT, None, None]:
        """Context manager for temporary scenes."""

    @abstractmethod
    def import_with_temp(self, file_path: str, target: JbContainerT) -> None:
        """Import a file into an isolated scene, then copy to target collection."""

    @abstractmethod
    def export_with_temp(self, src: list[JbObjectT | JbContainerT], ext: str) -> Optional[str]:
        """Copy objects to isolated scene, replace instances, export."""

    @abstractmethod
    def get_project_filepath(self) -> Optional[str]:
        """Return the current project filepath, if it exists."""

    @abstractmethod
    def solo(self):
        """Solo mode with history"""


class JbMaterialImporterABC(ABC, Generic[JbMaterialT]):
    """Abstract base class for Material Importers."""

    @abstractmethod
    def get_material_name(self, material: JbMaterialT) -> str | None:
        """Get the name of a material."""

    @abstractmethod
    def set_material_name(self, material: JbMaterialT, name: str):
        """Set the name of a material."""

    @abstractmethod
    def import_material(self, asset: AssetModel, file: AssetFile) -> Optional[JbMaterialT]:
        """Import a single material file into the scene."""


class JbSettingsABC(ABC, Generic[JbContainerT]):
    """Abstract base class for per-scene settings storage."""

    @abstractmethod
    def get_export_format(self) -> str:
        """Return the current export format (e.g. 'fbx', 'abc')."""

    @abstractmethod
    def load_solo_stack(self) -> list[list]:
        """Return the full solo-mode history as a list of container lists."""

    @abstractmethod
    def save_solo_selection(self, containers: list[JbContainerT]) -> None:
        """Push a new solo selection onto the history stack.

        No-op if the selection is identical to the most recent entry.
        """

    @abstractmethod
    def pop_solo_selection(self) -> list:
        """Remove the current selection and return the previous one.

        Returns an empty list if there is no previous entry.
        """


class JbAssetImporterABC(ABC, Generic[JbContainerT, JbObjectT, JbMaterialT]):
    """Abstract base class for Asset Importers.

    The source document is taken by ``__init__`` and is deliberately not part of
    the contract: it describes the interface of an instance, not how it is built.
    """

    @abstractmethod
    def import_assets(self) -> None:
        """Imports assets by selection."""

    @abstractmethod
    def import_message(self) -> str:
        """Return a confirmation message based on the current selection."""

    @abstractmethod
    def _collect_data(self) -> tuple[list[JbMaterialT], list[JbContainerT]]: ...

    @abstractmethod
    def _collect_assets(self) -> list[AssetModel]: ...

    @abstractmethod
    def _import_single(self, asset: AssetModel) -> None: ...

    @abstractmethod
    def _create_model(self, asset: AssetModel, file: AssetFile) -> JbContainerT: ...

    @abstractmethod
    def _convert_to_instances(self, container: JbContainerT) -> None: ...

    @abstractmethod
    def _resolve_placeholder(
        self, obj: JbObjectT, container: JbContainerT, asset_model: AssetModel
    ) -> JbContainerT | None: ...


class JbAssetExporterABC(ABC, Generic[JbContainerT, JbObjectT, JbMaterialT]):
    """Abstract base class for Asset Exporters.

    As in the importer contract, the source document is constructor-only and is
    therefore not part of the interface.
    """

    @abstractmethod
    def export_asset(self) -> None:
        """Exports an asset from the scene into Jiko Bridge."""

    @abstractmethod
    def export_message(self) -> str:
        """Return a confirmation message based on the current selection and asset containers."""

    @abstractmethod
    def _collect_data(
        self,
    ) -> tuple[list[JbContainerT | JbObjectT | JbMaterialT], list[JbContainerT]]: ...

    @abstractmethod
    def _update_asset(self, container: JbContainerT) -> None: ...

    @abstractmethod
    def _create_new_asset(self, objects: list[JbObjectT]) -> None: ...


class JbAPIABC(ABC):
    """Abstract base class for Jiko Bridge API interactions."""

    @abstractmethod
    def get_active_asset(self) -> Optional[AssetModel]:
        """Get the currently active asset based on selection or context."""

    @abstractmethod
    def get_asset_by_search(self, search_key: str) -> Optional[AssetModel]:
        """Search for an Asset by a free-form key."""

    @abstractmethod
    def get_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        """Get Asset by an AssetModel object."""

    @abstractmethod
    def create_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        """Create a new Asset with the given files and optional metadata."""

    @abstractmethod
    def update_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        """Update an existing Asset's files and metadata."""


# --- jiko_bridge_client.logger ---

JB_ENV = os.getenv('JB_ENV', 'production')
_DEFAULT_LEVEL = logging.INFO if JB_ENV == 'production' else logging.DEBUG


def get_logger(name: str, level: int | None = None) -> logging.Logger:
    """Return a logger with a single console handler.

    Calling this twice for the same name returns the already configured
    logger untouched, so imports are safe.
    """
    logger = logging.getLogger(name)
    if logger.handlers:
        return logger
    logger.setLevel(level if level is not None else _DEFAULT_LEVEL)
    formatter = logging.Formatter(
        '[Jiko Bridge] %(levelname)s [%(name)s] %(message)s', datefmt='%H:%M:%S'
    )
    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG)
    console.setFormatter(formatter)
    logger.addHandler(console)
    logger.propagate = False
    return logger


def _pretty(value: Any) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False)


def _error_body(error: BaseException) -> str:
    """Best-effort read of an HTTP error response body."""
    try:
        return getattr(error, 'read')().decode(errors='replace').strip() or '-'
    except (AttributeError, OSError):
        return '-'


def log_http(
    logger: logging.Logger,
    method: str,
    endpoint: str,
    payload: Optional[dict] = None,
    response: Optional[dict] = None,
    error: Optional[BaseException] = None,
) -> None:
    """Log one HTTP exchange: what was sent, then the reply or the failure."""
    sent = f'{method} {endpoint}'
    if payload is not None:
        sent += '\n' + _pretty(payload)
    if error is None:
        logger.debug('API response: %s\n%s', sent, _pretty(response))
    elif isinstance(error, urllib.error.HTTPError):
        logger.error(
            'JB_API HTTP error: %s %s\nRequest: %s\nResponse: %s',
            error.code,
            error.reason,
            sent,
            _error_body(error),
        )
    else:
        logger.exception('JB_API error: %s\nRequest: %s', error, sent)


# --- jiko_bridge_client.api ---

DEFAULT_PORT = 5174
logger = get_logger('jiko_bridge_client.api')


def _get_port() -> int:
    """Read the API port from the Jiko Bridge desktop app settings.

    Falls back to DEFAULT_PORT when the settings file is missing or
    unreadable, so the client always has a usable address.
    """
    system = platform.system()
    if system == 'Windows':
        path = os.path.join(os.getenv('APPDATA', ''), 'jiko-bridge', 'settings.json')
    elif system == 'Darwin':
        path = os.path.expanduser('~/Library/Application Support/jiko-bridge/settings.json')
    else:
        base = os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
        path = os.path.join(base, 'jiko-bridge', 'settings.json')
    try:
        with open(path, 'r', encoding='utf-8') as f:
            port = json.load(f).get('apiPort')
        if isinstance(port, int):
            return port
    except (OSError, json.JSONDecodeError):
        pass
    return DEFAULT_PORT


class JbAPI(JbAPIABC):
    """Client for communicating with the Jiko Bridge API server."""

    def __init__(self, host: str = 'localhost', port: Optional[int] = None):
        self.base_url = f'http://{host}:{port or _get_port()}'

    def _request(
        self, endpoint: str, payload: Optional[dict] = None, method: str = 'GET', timeout: int = 15
    ) -> Optional[dict]:
        url = f'{self.base_url}{endpoint}'
        data = json.dumps(payload).encode() if payload else None
        headers = {'Content-Type': 'application/json'} if data else {}
        try:
            req = urllib.request.Request(url, data=data, headers=headers, method=method)
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                parsed = json.loads(resp.read().decode())
                pretty = json.dumps(parsed, indent=2, ensure_ascii=False)
                logger.debug('API response: %s %s\n%s', method, endpoint, pretty)
                return parsed
        except urllib.error.HTTPError as e:
            logger.error('JB_API HTTP error: %s %s', e.code, e.reason)
            return None
        except (urllib.error.URLError, json.JSONDecodeError, OSError) as e:
            logger.exception('JB_API error: %s', e)
            return None

    def _asset_from_response(self, resp: Optional[dict]) -> Optional[AssetModel]:
        payload = (resp or {}).get('data')
        if not payload:
            return None
        return AssetModel.from_dict(payload)

    def get_active_asset(self) -> Optional[AssetModel]:
        return self._asset_from_response(self._request('/api/asset/active'))

    def get_asset_by_search(self, search_key) -> Optional[AssetModel]:
        return self._asset_from_response(
            self._request('/api/asset', {'searchKey': search_key}, method='POST')
        )

    def get_asset(self, asset) -> Optional[AssetModel]:
        return self._asset_from_response(
            self._request('/api/asset', asset.to_dict(), method='POST')
        )

    def create_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        return self._asset_from_response(
            self._request('/api/asset/create', asset.to_dict(), method='POST', timeout=300)
        )

    def update_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        return self._asset_from_response(
            self._request('/api/asset/update', asset.to_dict(), method='POST', timeout=30)
        )


# --- jiko_bridge_client ---

# Jiko Bridge client.
#
# Shared models, HTTP API client and integration contracts used by every
# Jiko Bridge DCC plugin (Blender, Cinema 4D, Maya, Houdini).
#
#     from jiko_bridge_client import JbAPI, AssetModel, AssetFile
#
# Code by Semyon Shapoval, 2026


# --- jiko_bridge_c4d.jb_types ---

JbSource: TypeAlias = c4d.documents.BaseDocument
JbMatrix: TypeAlias = c4d.Matrix
JbContainer: TypeAlias = c4d.BaseObject
JbObject: TypeAlias = c4d.BaseObject
JbMaterial: TypeAlias = c4d.BaseMaterial
JbData: TypeAlias = JbContainer | JbObject | JbMaterial
JbSceneBase: TypeAlias = JbSceneABC[JbSource, JbMatrix, JbContainer, JbObject, JbMaterial]
JbMaterialImporterBase: TypeAlias = JbMaterialImporterABC[JbMaterial]
JbSettingsBase: TypeAlias = JbSettingsABC[JbContainer]
JbAssetImporterBase: TypeAlias = JbAssetImporterABC[JbContainer, JbObject, JbMaterial]
JbAssetExporterBase: TypeAlias = JbAssetExporterABC[JbContainer, JbObject, JbMaterial]

# --- jiko_bridge_c4d.jb_settings ---

IDC_SETTINGS_COMBO = 3001
IDC_SETTINGS_OK = 3002
IDC_SETTINGS_CANCEL = 3003
COMBO_OPTIONS_EXPORT_FORMAT = ['fbx', 'abc']


class JbSettings(JbSettingsBase):
    """Manages plugin settings stored inside the C4D document."""

    _SETTINGS_ID = 1096087
    _SOLO_STACK_ID = 1057892
    _SOLO_STACK_SIZE = 10
    _SETTING_EXPORT_FORMAT = 1057234

    def __init__(self, doc: c4d.documents.BaseDocument):
        self._doc = doc

    def _get_container(self) -> c4d.BaseContainer:
        return self._doc.GetDataInstance().GetContainer(self._SETTINGS_ID)

    def _save_container(self, bc: c4d.BaseContainer) -> None:
        self._doc.GetDataInstance().SetContainer(self._SETTINGS_ID, bc)

    def _entry_to_bc(self, objects: list) -> c4d.BaseContainer:
        bc = c4d.BaseContainer()
        for i, obj in enumerate(objects):
            bc.SetLink(i, obj)
        return bc

    def _bc_to_entry(self, bc: c4d.BaseContainer) -> list:
        return [obj for _, obj in bc if isinstance(obj, c4d.BaseObject) and obj.IsAlive()]

    def get_export_format(self) -> str:
        """Return the export format stored in the document."""
        bc = self._get_container()
        index = bc.GetInt32(self._SETTING_EXPORT_FORMAT, 0)
        return COMBO_OPTIONS_EXPORT_FORMAT[index]

    def set_export_format(self, index: int) -> None:
        """Set export format for exporting"""
        bc = self._get_container()
        bc.SetInt32(self._SETTING_EXPORT_FORMAT, index)
        self._save_container(bc)

    def load_solo_stack(self) -> list[list]:
        """Return the stored solo selections, newest first."""
        root_bc = self._doc.GetDataInstance().GetContainer(self._SOLO_STACK_ID)
        return [
            self._bc_to_entry(root_bc.GetContainer(i))
            for i in range(self._SOLO_STACK_SIZE)
            if root_bc.FindIndex(i) != -1
        ]

    def save_solo_selection(self, containers) -> None:
        """Push a solo selection onto the stored stack."""
        stack = self.load_solo_stack()
        if stack:
            previous_selection = stack[0]
            if set(containers) == set(previous_selection):
                return
        stack.insert(0, containers)
        stack = stack[: self._SOLO_STACK_SIZE]
        root_bc = c4d.BaseContainer()
        for i, entry in enumerate(stack):
            root_bc.SetContainer(i, self._entry_to_bc(entry))
        self._doc.GetDataInstance().SetContainer(self._SOLO_STACK_ID, root_bc)

    def pop_solo_selection(self) -> list:
        """Return the previous solo selection and drop it from the stack."""
        stack = self.load_solo_stack()
        if len(stack) < 2:
            return []
        _, previous, *rest = stack
        root_bc = c4d.BaseContainer()
        for i, entry in enumerate([previous] + rest):
            root_bc.SetContainer(i, self._entry_to_bc(entry))
        self._doc.GetDataInstance().SetContainer(self._SOLO_STACK_ID, root_bc)
        return previous


class JbSettingsDialog(c4d.gui.GeDialog):
    """Dialog with settings jiko bridge."""

    def __init__(self, doc: c4d.documents.BaseDocument):
        super().__init__()
        self._settings = JbSettings(doc)
        self.selected_option = 0

    def CreateLayout(self):
        """Create layout"""
        self.SetTitle('Settings')
        self.GroupBegin(0, c4d.BFH_SCALEFIT, 1, 0, '', 0)
        self.GroupBorderSpace(10, 10, 10, 10)
        self.AddStaticText(0, c4d.BFH_LEFT, name='Export Format:')
        self.AddComboBox(IDC_SETTINGS_COMBO, c4d.BFH_SCALEFIT)
        for i, label in enumerate(COMBO_OPTIONS_EXPORT_FORMAT):
            self.AddChild(IDC_SETTINGS_COMBO, i, label)
        self.GroupEnd()
        self.GroupBegin(0, c4d.BFH_CENTER, 2, 1, '', 0)
        self.GroupBorderSpace(10, 5, 10, 10)
        self.AddButton(IDC_SETTINGS_OK, c4d.BFH_SCALE, name='OK')
        self.AddButton(IDC_SETTINGS_CANCEL, c4d.BFH_SCALE, name='Cancel')
        self.GroupEnd()
        return True

    def InitValues(self):
        index = COMBO_OPTIONS_EXPORT_FORMAT.index(self._settings.get_export_format())
        self.SetInt32(IDC_SETTINGS_COMBO, index)
        return True

    def Command(self, cmd_id, _msg):
        if cmd_id == IDC_SETTINGS_OK:
            self._settings.set_export_format(self.GetInt32(IDC_SETTINGS_COMBO))
            self.Close()
        elif cmd_id == IDC_SETTINGS_CANCEL:
            self.Close()
        return True


# --- jiko_bridge_c4d.scene.jb_scene_objects ---


class JbSceneObjects(JbSceneBase):
    """Traversal and querying of Cinema 4D object hierarchies."""

    def get_selection(self) -> list[JbObject | JbMaterial]:
        result = []
        materials = self.source.GetActiveMaterials()
        if materials:
            result.extend(materials)
        objects = self.source.GetActiveObjects(c4d.GETACTIVEOBJECTFLAGS_0)
        if objects:
            result.extend(objects)
        return result

    def walk(self, root) -> list[JbData]:
        if not root:
            return []
        return list(self._walk(root))

    def _walk(self, root: list[JbData]):
        if root is None:
            return

        def walk_objects(obj):
            yield obj
            child = obj.GetDown()
            while child:
                yield from walk_objects(child)
                child = child.GetNext()

        for item in root:
            if isinstance(item, c4d.BaseObject):
                yield from walk_objects(item)
            elif isinstance(item, c4d.BaseMaterial):
                yield item

    def get_materials_from_objects(self, objects) -> list[JbMaterial]:
        materials = []
        for obj in objects:
            if isinstance(obj, c4d.BaseMaterial):
                materials.append(obj)
                continue
            if not obj.IsInstanceOf(c4d.Opolygon):
                continue
            for tag in obj.GetTags():
                if not tag.CheckType(c4d.Ttexture):
                    continue
                material = tag[c4d.TEXTURETAG_MATERIAL]
                if material:
                    materials.append(material)
        return materials

    def get_children(self, obj) -> list[JbObject]:
        return obj.GetChildren() or []

    def copy_object_transform(self, obj, target_obj) -> None:
        obj.SetMg(target_obj.GetMg())

    def remove_object(self, obj) -> None:
        obj.Remove()

    def get_depth(self, obj) -> int:
        depth = 0
        current = obj
        while current.GetUp():
            depth += 1
            current = current.GetUp()
        return depth

    def _set_protection_tag(self, obj: c4d.BaseObject) -> None:
        if obj is None:
            return
        if obj.GetTags() is not None:
            for tag in obj.GetTags():
                try:
                    if tag.GetType() == c4d.Tprotection:
                        tag[c4d.PROTECTION_ALLOW_DUPLICATION] = True
                        return
                except (AttributeError, TypeError):
                    continue
        try:
            protection_tag = c4d.BaseTag(c4d.Tprotection)
            if protection_tag is not None:
                protection_tag[c4d.PROTECTION_ALLOW_DUPLICATION] = True
                obj.InsertTag(protection_tag)
        except (AttributeError, TypeError):
            pass

    def _set_user_data(self, obj: c4d.BaseObject, name: str, value: str | None) -> None:
        if value is None:
            value = ''
        for key, bc in obj.GetUserDataContainer() or []:
            if bc[c4d.DESC_NAME] == name:
                obj[key] = value
                return
        bc = c4d.GetCustomDatatypeDefault(c4d.DTYPE_STRING)
        bc[c4d.DESC_NAME] = name
        bc[c4d.DESC_SHORT_NAME] = name
        bc[c4d.DESC_DEFAULT] = value
        element = obj.AddUserData(bc)
        if element is not None:
            obj[element] = value

    def _set_visibility(self, obj: c4d.BaseObject, mode: int) -> None:
        obj[c4d.ID_BASEOBJECT_VISIBILITY_EDITOR] = mode
        obj[c4d.ID_BASEOBJECT_VISIBILITY_RENDER] = mode

    def merge_duplicates_materials(self, material: c4d.BaseMaterial) -> None:
        pattern = re.compile('^' + re.escape(material.GetName()) + '\\.\\d+$')
        duplicates = set()
        mat = self.source.GetFirstMaterial()
        while mat:
            if pattern.match(mat.GetName()):
                duplicates.add(mat)
            mat = mat.GetNext()
        if not duplicates:
            return
        for obj in self.walk(self.source.GetObjects()):
            while obj:
                tag = obj.GetFirstTag()
                while tag:
                    if tag.GetType() == c4d.Ttexture:
                        if tag[c4d.TEXTURETAG_MATERIAL] in duplicates:
                            tag[c4d.TEXTURETAG_MATERIAL] = material
                    tag = tag.GetNext()
        for dup in duplicates:
            dup.Remove()


# --- jiko_bridge_c4d.scene.jb_scene_container ---


class JbSceneContainer(JbSceneObjects):
    """Container and asset management: null objects, user data, collections."""

    def get_container(self, asset):
        doc = self.source
        name = f'Asset_{asset.pack_name}_{asset.asset_name}'
        return doc.SearchObject(name)

    def get_or_create_container(self, name, parent=None) -> tuple[JbContainer, bool]:
        doc = self.source
        obj = doc.SearchObject(name)
        existed = obj is not None
        if not existed:
            obj = c4d.BaseObject(c4d.Onull)
            if parent is not None:
                obj.InsertUnder(parent)
            else:
                doc.InsertObject(obj)
        obj.SetName(name)
        obj[c4d.ID_BASELIST_ICON_FILE] = '12499'
        obj[c4d.ID_BASELIST_ICON_COLORIZE_MODE] = c4d.ID_BASELIST_ICON_COLORIZE_MODE_CUSTOM
        obj[c4d.ID_BASELIST_ICON_COLOR] = c4d.Vector(0.071, 0.949, 0.85)
        return (obj, existed)

    def get_or_create_asset_container(self, asset, file=None) -> tuple[JbContainer, bool]:
        """Get or create an asset container null with user data from the asset and file."""
        root_null, _ = self.get_or_create_container('Assets')
        self._set_protection_tag(root_null)
        asset_null, asset_existed = self.get_or_create_container(
            f'Asset_{asset.pack_name}_{asset.asset_name}', parent=root_null
        )
        self._set_protection_tag(asset_null)
        self._set_user_data(asset_null, 'vaultName', asset.vault_name)
        self._set_user_data(asset_null, 'packName', asset.pack_name)
        self._set_user_data(asset_null, 'assetName', asset.asset_name)
        if file:
            self._set_user_data(asset_null, 'assetType', file.asset_type)
        if len(asset_null.GetChildren()) == 0:
            asset_existed = False
        return (asset_null, asset_existed)

    def set_asset_data(self, container, asset, file=None) -> None:
        self._set_user_data(container, 'vaultName', asset.vault_name)
        self._set_user_data(container, 'packName', asset.pack_name)
        self._set_user_data(container, 'assetName', asset.asset_name)
        if file:
            self._set_user_data(container, 'assetType', file.asset_type)

    def get_asset_data_from_container(self, container) -> Optional[AssetModel]:
        pack_name = asset_name = asset_type = vault_name = None
        for key, bc in container.GetUserDataContainer() or []:
            bc_name = bc[c4d.DESC_NAME]
            if bc_name == 'packName':
                pack_name = container[key]
            elif bc_name == 'assetName':
                asset_name = container[key]
            elif bc_name == 'assetType':
                asset_type = container[key] or None
            elif bc_name == 'vaultName':
                vault_name = container[key] or None
        if not (pack_name and asset_name):
            return None
        return AssetModel(
            pack_name=pack_name,
            asset_name=asset_name,
            active_type=asset_type,
            vault_name=vault_name,
        )

    def copy_asset_data(self, src, dst) -> None:
        for key, bc in src.GetUserDataContainer():
            name = bc[c4d.DESC_NAME]
            value = src[key]
            self._set_user_data(dst, name, value)

    def get_containers_from_objects(self, objects) -> list[JbContainer]:
        return [
            obj
            for obj in objects
            if obj.CheckType(c4d.Onull) and self.get_asset_data_from_container(obj) is not None
        ]

    def get_containers_from_instances(self, objects) -> list[JbContainer]:
        containers = []
        for obj in objects:
            if not obj.CheckType(c4d.Oinstance):
                continue
            linked = obj[c4d.INSTANCEOBJECT_LINK]
            if linked is None or not linked.IsAlive():
                continue
            if self.get_asset_data_from_container(linked) is not None:
                containers.append(linked)
        return containers

    def move_objects_to_container(self, objects, container) -> None:
        """Unified API: re-parents objects under asset null."""
        for obj in objects:
            obj.Remove()
            obj.InsertUnder(container)

    def cleanup_container(self, container) -> None:
        count = 0
        objects = self.walk(container.GetChildren())
        for obj in objects:
            if obj.GetType() == c4d.Onull and len(obj.GetChildren()) == 0:
                count += 1
                obj.Remove()
            elif obj.GetType() == c4d.Oalembicgenerator and len(obj.GetChildren()) == 0:
                has_geometry = obj[c4d.ALEMBIC_UPDATE_GEOMETRY]
                if not has_geometry:
                    count += 1
                    obj.Remove()
        if count > 0:
            self.logger.debug('Cleanup empty nulls: %s', count)
        c4d.CallCommand(12168)

    def clear_container(self, container) -> None:
        """Unified API: remove all children from asset null."""
        for child in container.GetChildren():
            child.Remove()


# --- jiko_bridge_c4d.scene.jb_scene_instance ---


class JbSceneInstance(JbSceneContainer):
    """Instance and placeholder management for Cinema 4D."""

    def create_instance(self, container, name):
        instance = c4d.BaseObject(c4d.Oinstance)
        instance.SetName(f'Instance_{name}')
        instance[c4d.INSTANCEOBJECT_LINK] = container
        instance[c4d.INSTANCEOBJECT_RENDERINSTANCE_MODE] = 1
        for key, bc in container.GetUserDataContainer():
            self._set_user_data(instance, bc[c4d.DESC_NAME], container[key])
        self.source.InsertObject(instance)
        instance.SetBit(c4d.BIT_ACTIVE)
        return instance

    def get_names_from_placeholder(self, obj) -> List[str]:
        names = set()
        if not obj.IsInstanceOf(c4d.Opolygon) and obj.GetType() != 1028083:
            return []
        if obj.IsInstanceOf(c4d.Opolygon) and obj.GetPointCount() != 4:
            return []
        for tag in obj.GetTags():
            if tag.CheckType(c4d.Ttexture):
                material = tag[c4d.TEXTURETAG_MATERIAL] if tag.GetType() == c4d.Ttexture else None
                if material:
                    names.add(material.GetName())
            elif tag.GetType() == 1036433:
                name = tag.GetName()
                if name:
                    names.add(name)
            elif tag.CheckType(c4d.Tpolygonselection):
                selection_name = tag.GetName()
                if selection_name:
                    names.add(selection_name)
        return list(names)

    def replace_instances_with_placeholders(self, objects, source) -> list[JbObject]:
        if not objects:
            return []
        new_objects = []
        for obj in objects:
            if not obj.CheckType(c4d.Oinstance):
                continue
            info = self.get_asset_data_from_container(obj)
            if not info:
                continue
            placeholder = self.create_placeholder(info, obj.GetMg(), source)
            source.InsertObject(placeholder)
            new_objects.append(placeholder)
            obj.Remove()
        return new_objects

    def create_placeholder(self, asset_model, transform, source) -> JbObject:
        pack_name = asset_model.pack_name
        asset_name = asset_model.asset_name
        name = f'{pack_name}__{asset_name}'
        material = c4d.BaseMaterial(c4d.Mmaterial)
        material.SetName(name)
        source.InsertMaterial(material)
        prim = c4d.BaseObject(c4d.Oplane)
        prim[c4d.PRIM_PLANE_WIDTH] = 100
        prim[c4d.PRIM_PLANE_HEIGHT] = 100
        prim[c4d.PRIM_PLANE_SUBW] = 1
        prim[c4d.PRIM_PLANE_SUBH] = 1
        obj = c4d.utils.SendModelingCommand(
            command=c4d.MCOMMAND_CURRENTSTATETOOBJECT,
            list=[prim],
            mode=c4d.MODELINGCOMMANDMODE_ALL,
            doc=self.source,
        )
        if obj and len(obj) > 0:
            obj = obj[0]
        else:
            obj = prim
        obj.SetMg(transform)
        obj.SetName(name)
        stag = obj.MakeTag(c4d.Tpolygonselection)
        stag.SetName(name)
        bs = stag.GetBaseSelect()
        bs.Select(0)
        mtag = obj.MakeTag(c4d.Ttexture)
        mtag[c4d.TEXTURETAG_MATERIAL] = material
        return obj


# --- jiko_bridge_c4d.scene.jb_scene_temp ---


class JbSceneTemp(JbSceneInstance):
    """Scene-level operations: document helpers, geometry transforms."""

    def __init__(self):
        self._temp_source = None

    @contextmanager
    def temp_source(self, objects=None, unit_scale=c4d.DOCUMENT_UNIT_CM, debug=False):
        if objects:
            tmp_doc = c4d.documents.IsolateObjects(self.source, objects)
        else:
            tmp_doc = c4d.documents.BaseDocument()
        self._temp_source = tmp_doc
        unit_scale_data = c4d.UnitScaleData()
        unit_scale_data.SetUnitScale(1, unit_scale)
        tmp_doc[c4d.DOCUMENT_DOCUNIT] = unit_scale_data
        try:
            yield tmp_doc
        finally:
            if debug:
                c4d.documents.InsertBaseDocument(tmp_doc)
                c4d.documents.SetActiveDocument(tmp_doc)
                c4d.EventAdd()
            else:
                c4d.documents.KillDocument(tmp_doc)
            self._temp_source = None

    def _copy_source(
        self,
        src: c4d.documents.BaseDocument,
        dst: c4d.documents.BaseDocument,
        parent: c4d.BaseObject,
    ) -> None:
        mat = src.GetFirstMaterial()
        while mat:
            next_mat = mat.GetNext()
            mat.Remove()
            dst.InsertMaterial(mat)
            mat = next_mat
        objects = src.GetObjects()
        for obj in objects:
            obj.Remove()
            dst.InsertObject(obj)
            obj.InsertUnder(parent)
            obj.SetBit(c4d.BIT_ACTIVE)

    def _project_scale(self, doc: c4d.documents.BaseDocument, factor: float = 0.01) -> None:
        objects = self.walk(doc.GetObjects())
        for obj in objects:
            if obj.IsInstanceOf(c4d.Opolygon):
                points = obj.GetAllPoints()
                if points:
                    obj.SetAllPoints([p * factor for p in points])
                    obj.Message(c4d.MSG_UPDATE)
            pos = obj.GetRelPos()
            obj.SetRelPos(pos * factor)
        self.logger.debug('Project scale: %s objects', len(objects))

    def _make_editable(self, objects: list[c4d.BaseObject]) -> None:
        """Convert generators to polygons (MCOMMAND_MAKEEDITABLE)."""
        count = 0
        for item in objects:
            if not item.IsAlive():
                continue
            if item.IsInstanceOf(c4d.Opolygon) or item.IsInstanceOf(c4d.Onull):
                continue
            parent = item.GetUp()
            children = list(item.GetChildren())
            result = c4d.utils.SendModelingCommand(
                command=c4d.MCOMMAND_MAKEEDITABLE,
                list=[item],
                mode=c4d.MODELINGCOMMANDMODE_ALL,
                doc=self._temp_source,
            )
            if isinstance(result, list):
                for new_obj in result:
                    count += 1
                    self._temp_source.InsertObject(new_obj)
                    if parent:
                        new_obj.InsertUnder(parent)
                    for child in children:
                        child.Remove()
                        child.InsertUnder(new_obj)
        if count > 0:
            self.logger.debug('Editable: %s objects', count)

    def _remove_unused_materials(self, doc: c4d.documents.BaseDocument) -> None:
        used_mats = set()
        objects = self.walk(doc.GetObjects())
        for obj in objects:
            tag = obj.GetFirstTag()
            while tag:
                if tag.GetType() == c4d.Ttexture:
                    mat = tag[c4d.TEXTURETAG_MATERIAL]
                    if mat is not None:
                        used_mats.add(mat)
                tag = tag.GetNext()
        mat = doc.GetFirstMaterial()
        while mat:
            next_mat = mat.GetNext()
            if mat not in used_mats:
                mat.Remove()
            mat = next_mat


# --- jiko_bridge_c4d.scene.jb_scene_file ---


class JbSceneFile(JbSceneTemp):
    """File import/export layer in the scene hierarchy."""

    def __init__(self):
        super().__init__()
        self.cache_path = os.path.join(tempfile.gettempdir(), 'jiko-bridge')
        os.makedirs(self.cache_path, exist_ok=True)

    def _find_plugin(self, plugin_id: int, plugin_type: int) -> Optional[c4d.plugins.BasePlugin]:
        plug = c4d.plugins.FindPlugin(plugin_id, plugin_type)
        if not plug:
            self.logger.error('Plugin %d not found', plugin_id)
        return plug

    def _get_imexporter(self, plug: c4d.plugins.BasePlugin) -> Optional[MutableMapping[int, Any]]:
        data: dict[str, Any] = {}
        if not plug.Message(c4d.MSG_RETRIEVEPRIVATEDATA, data):
            self.logger.error('Failed to retrieve private data from plugin')
            return None
        imexporter = data.get('imexporter')
        if not imexporter:
            self.logger.error('imexporter not available in plugin data')
        return imexporter

    def _merge_document(self, file_path: str) -> bool:
        doc = self._temp_source
        if doc is None:
            self.logger.error('No active document for merging')
            return False
        t = time.time()
        result = c4d.documents.MergeDocument(
            doc, file_path, c4d.SCENEFILTER_OBJECTS | c4d.SCENEFILTER_MATERIALS
        )
        self.logger.debug('Import took %.3fs: %s', time.time() - t, file_path)
        return result

    def _save_document(self, file_path: str, format_id: int) -> bool:
        doc = self._temp_source
        if doc is None:
            self.logger.error('No active document for saving')
            return False
        t = time.time()
        result = c4d.documents.SaveDocument(doc, file_path, c4d.SAVEDOCUMENTFLAGS_NONE, format_id)
        self.logger.debug('Export took %.3fs: %s', time.time() - t, file_path)
        return result

    def import_file(self, file_path) -> bool:
        ext = Path(file_path).suffix.lower().lstrip('.')
        handler = {
            'fbx': self._import_fbx,
            'abc': self._import_alembic,
            'obj': self._import_obj,
            'usd': self._import_usd,
        }.get(ext)
        if not handler:
            self.logger.error('Unsupported file extension: %s', ext)
            return False
        return handler(file_path)

    def _import_fbx(self, file_path) -> bool:
        plug = self._find_plugin(c4d.FORMAT_FBX_IMPORT, c4d.PLUGINTYPE_SCENELOADER)
        if not plug:
            return False
        imex = self._get_imexporter(plug)
        if imex:
            imex[c4d.FBXIMPORT_CAMERAS] = True
            imex[c4d.FBXIMPORT_LIGHTS] = True
            imex[c4d.FBXIMPORT_SINGLE_MAT_SELECTIONTAGS] = False
        result = self._merge_document(file_path)
        if not result:
            self.logger.error('FBX import failed: %s', file_path)
        return result

    def _import_alembic(self, file_path: str) -> bool:
        plug = self._find_plugin(c4d.FORMAT_ABCIMPORT, c4d.PLUGINTYPE_SCENELOADER)
        if not plug:
            return False
        imex = self._get_imexporter(plug)
        if imex:
            scale_data = c4d.UnitScaleData()
            scale_data.SetUnitScale(1, c4d.DOCUMENT_UNIT_M)
            imex[c4d.ABCIMPORT_SCALE] = scale_data
            imex[c4d.ABCIMPORT_FACESETS] = True
        result = self._merge_document(file_path)
        if not result:
            self.logger.error('Alembic import failed: %s', file_path)
        return result

    def _import_obj(self, file_path: str) -> bool:
        plug = self._find_plugin(c4d.FORMAT_OBJ2IMPORT, c4d.PLUGINTYPE_SCENELOADER)
        if not plug:
            return False
        result = self._merge_document(file_path)
        if not result:
            self.logger.error('OBJ import failed: %s', file_path)
        return result

    def _import_usd(self, file_path: str) -> bool:
        plug = self._find_plugin(c4d.FORMAT_USDIMPORT, c4d.PLUGINTYPE_SCENELOADER)
        if not plug:
            return False
        result = self._merge_document(file_path)
        if not result:
            self.logger.error('USD import failed: %s', file_path)
        return result

    def _generate_path(self, ext: str) -> str:
        filename = f'tmp_{int(time.time())}.{ext}'
        return os.path.join(self.cache_path, filename)

    def _select_all(self, doc: c4d.documents.BaseDocument) -> None:
        objects = self.walk(doc.GetObjects())
        for obj in objects:
            obj.SetBit(c4d.BIT_ACTIVE)

    def export_file(self, ext) -> Optional[str]:
        file_path = self._generate_path(ext)
        handler = {
            'fbx': self._export_fbx,
            'abc': self._export_alembic,
            'obj': self._export_obj,
            'usd': self._export_usd,
        }.get(ext)
        if not handler:
            self.logger.error('Unsupported export extension: %s', ext)
            return None
        self._select_all(self._temp_source)
        return handler(file_path)

    def _export_fbx(self, file_path) -> Optional[str]:
        self._project_scale(self._temp_source, 0.01)
        plug = self._find_plugin(c4d.FORMAT_FBX_EXPORT, c4d.PLUGINTYPE_SCENESAVER)
        if not plug:
            return None
        imex = self._get_imexporter(plug)
        if imex:
            imex[c4d.FBXEXPORT_SELECTION_ONLY] = True
            imex[c4d.FBXEXPORT_ASCII] = False
            imex[c4d.FBXEXPORT_SCALE] = 0.01
            imex[c4d.FBXEXPORT_EMBED_TEXTURES] = False
        if not self._save_document(file_path, c4d.FORMAT_FBX_EXPORT):
            self.logger.error('FBX export failed')
            return None
        self.logger.debug('FBX exported: %s', file_path)
        return file_path

    def _export_alembic(self, file_path: str) -> Optional[str]:
        self._project_scale(self._temp_source, 0.01)
        plug = self._find_plugin(c4d.FORMAT_ABCEXPORT, c4d.PLUGINTYPE_SCENESAVER)
        if not plug:
            return None
        imex = self._get_imexporter(plug)
        if imex:
            imex[c4d.ABCEXPORT_SELECTION_ONLY] = True
            scale_data = c4d.UnitScaleData()
            scale_data.SetUnitScale(1, c4d.DOCUMENT_UNIT_M)
            imex[c4d.ABCEXPORT_SCALE] = scale_data
        if not self._save_document(file_path, c4d.FORMAT_ABCEXPORT):
            self.logger.error('Alembic export failed')
            return None
        self.logger.debug('Alembic exported: %s', file_path)
        return file_path

    def _export_obj(self, _file_path: str) -> Optional[str]:
        return None

    def _export_usd(self, _file_path: str) -> Optional[str]:
        return None


# --- jiko_bridge_c4d.scene.jb_scene ---


class JbScene(JbSceneFile):
    """High-level import / export operations for the active C4D scene."""

    def __init__(self, source: JbSource):
        super().__init__()
        self._source = source
        self._logger = get_logger('jiko_bridge_c4d.scene.jb_scene')

    @property
    def logger(self) -> Logger:
        return self._logger

    @property
    def source(self) -> JbSource:
        if self._source is None:
            self._source = c4d.documents.GetActiveDocument()
        return self._source

    def import_with_temp(self, file_path, target) -> None:
        with self.temp_source(debug=False) as tmp_doc:
            if not self.import_file(file_path):
                self.logger.warning('No objects imported for file: %s', file_path)
                return
            self._copy_source(tmp_doc, self.source, target)

    def export_with_temp(self, src, ext) -> Optional[str]:
        for obj in src:
            if obj.CheckType(c4d.Oinstance):
                linked = obj[c4d.INSTANCEOBJECT_LINK]
                if linked:
                    self.copy_asset_data(linked, obj)
        with self.temp_source(objects=src, unit_scale=c4d.DOCUMENT_UNIT_M, debug=False) as tmp_doc:
            objects = sorted(self.walk(tmp_doc.GetObjects()), key=self.get_depth, reverse=True)
            self.replace_instances_with_placeholders(objects, tmp_doc)
            tmp_doc.ExecutePasses(None, True, True, True, c4d.BUILDFLAGS_NONE)
            editable_objects = sorted(
                self.walk(tmp_doc.GetObjects()), key=self.get_depth, reverse=True
            )
            self._make_editable(editable_objects)
            return self.export_file(ext)

    def get_project_filepath(self) -> Optional[str]:
        path = self.source.GetDocumentPath()
        name = self.source.GetDocumentName()
        if path and name:
            return os.path.join(path, name)
        self.logger.warning('Please save the project before exporting.')
        return None

    def solo(self):
        objects = self.get_selection()
        instances = self.get_containers_from_instances(objects)
        containers = self.get_containers_from_objects(objects)
        combine = instances + containers
        settings = JbSettings(self.source)
        if not combine:
            combine = settings.pop_solo_selection()
        else:
            settings.save_solo_selection(combine)
        if not combine:
            return
        root, _ = self.get_or_create_container('Assets')
        self._set_visibility(root, 1)
        for child in root.GetChildren():
            self._set_visibility(child, 2)
        for obj in combine:
            self._set_visibility(obj, 0)
        c4d.CallCommand(12288)


# --- jiko_bridge_c4d.jb_asset_exporter ---

asset_export_logger = get_logger('jiko_bridge_c4d.jb_asset_exporter')


class JbAssetExporter(JbAssetExporterBase):
    """Export asset class"""

    def __init__(self, source: JbSource):
        self.source = source
        self.api = JbAPI()
        self.scene = JbScene(source)

    def export_asset(self) -> None:
        """Export the selected asset or create a new one."""
        selected_objects, asset_containers = self._collect_data()
        if asset_containers:
            for container in asset_containers:
                self._update_asset(container)
        elif selected_objects:
            self._create_new_asset(selected_objects)
        else:
            self._export_project()

    def export_message(self) -> str:
        selected_objects, asset_containers = self._collect_data()
        if asset_containers:
            return f'Update existing assets?\n{len(asset_containers)} asset(s) will be updated'
        if selected_objects:
            return f'No asset containers found in selection. Create new asset with {len(selected_objects)} object(s)?'
        return 'Export project.'

    def _collect_data(self):
        selected_objects = self.scene.get_selection()
        asset_containers = self.scene.get_containers_from_objects(selected_objects)
        return (selected_objects, asset_containers)

    def _update_asset(self, container) -> None:
        asset_model = self.scene.get_asset_data_from_container(container)
        if not asset_model:
            asset_export_logger.error('Invalid asset information')
            return
        asset = self.api.get_asset(asset_model)
        if not asset or not asset.files or (not asset.pack_name) or (not asset.asset_name):
            asset_export_logger.error("Failed to fetch asset '%s'.", asset_model.asset_name)
            return
        file = next(iter(asset.files))
        if not file.filepath:
            asset_export_logger.error(
                "Filepath missing for asset '%s'. Cannot export.", asset_model.asset_name
            )
            return
        ext = Path(file.filepath.lower()).suffix.lstrip('.')
        if not ext:
            asset_export_logger.error(
                "Unable to determine export extension from filepath '%s' for '%s'.",
                file.filepath,
                asset_model.asset_name,
            )
            return
        objects = self.scene.get_children(container)
        if not objects:
            asset_export_logger.error(
                "No objects found in container for asset '%s'. Cannot export.",
                asset_model.asset_name,
            )
            return
        filepath = self.scene.export_with_temp(objects, ext)
        if not filepath:
            return
        asset.files = [
            AssetFile(filepath=filepath, asset_type=file.asset_type, bridge_type=file.bridge_type)
        ]
        self.api.update_asset(asset)

    def _create_new_asset(self, objects) -> None:
        fmt = JbSettings(self.source).get_export_format()
        filepath = self.scene.export_with_temp(objects, fmt)
        if not filepath:
            asset_export_logger.error('Export failed.')
            return
        asset = self.api.create_asset(AssetModel(files=[AssetFile(filepath=filepath)]))
        if not asset or not asset.files:
            asset_export_logger.error("No asset found for filepath '%s'", filepath)
            return
        for file in asset.files:
            container, _ = self.scene.get_or_create_asset_container(asset, file)
            self.scene.move_objects_to_container(objects, container)
            asset_export_logger.info(
                "Asset '%s' created with type '%s'.", asset.asset_name, file.asset_type
            )

    def _export_project(self) -> None:
        if filepath := self.scene.get_project_filepath():
            self.api.create_asset(AssetModel(files=[AssetFile(filepath=filepath)]))


# --- jiko_bridge_c4d.materials.jb_base_node_material ---

node_material_logger = get_logger('jiko_bridge_c4d.materials.jb_base_node_material')
ASSET_ID_ATTR = 'net.maxon.node.attribute.assetid'
NODE_NAME_ID = 'net.maxon.node.base.name'
PortType = str | int
PortsType = PortType | list[PortType]


class JbBaseNodeMaterial:
    """Base node material."""

    def __init__(self):
        self._graph = None

    def nodespace_id(self) -> 'Optional[str]':
        """Returns the node space ID for this material type, or None if not applicable."""
        raise NotImplementedError

    @staticmethod
    def path_to_url(path: 'str') -> 'maxon.Url':
        """Converts a file path to a maxon.Url."""
        normalized = path.replace('\\', '/')
        if not normalized.startswith('/'):
            normalized = '/' + normalized
        return maxon.Url(f'file://{normalized}')

    @staticmethod
    def ensure_graph(material: 'c4d.BaseMaterial', nodespace_id: 'str'):
        """Возвращает граф, создавая его если нужно."""
        node_mat = material.GetNodeMaterialReference()
        if node_mat is None:
            return None
        if not node_mat.HasSpace(maxon.Id(nodespace_id)):
            node_mat.AddGraph(maxon.Id(nodespace_id))
        return node_mat.GetGraph(maxon.Id(nodespace_id))

    def _make_labeled_node(self, graph, asset_id: 'str', label: 'str'):
        """Ищет узел с именем label среди узлов asset_id; создаёт, если не найден."""
        for node in self.find_nodes_by_asset_id(graph, asset_id):
            try:
                if str(node.GetValue(NODE_NAME_ID)) == label:
                    return node
            except (AttributeError, TypeError, RuntimeError):
                pass
        node = self.add_node(graph, asset_id)
        try:
            node.SetValue(NODE_NAME_ID, maxon.String(label))
        except (AttributeError, TypeError, RuntimeError):
            pass
        return node

    @staticmethod
    def find_nodes_by_asset_id(graph, asset_id: 'str') -> 'list':
        """Ищет все узлы с данным asset ID через официальный GraphModelHelper.
        При неудаче — fallback через ручной обход дочерних узлов."""
        result: 'list[object]' = []
        try:
            maxon.GraphModelHelper.FindNodesByAssetId(graph, maxon.Id(asset_id), True, result)
        except (RuntimeError, TypeError, AttributeError):
            pass
        if not result:
            for child in graph.GetRoot().GetChildren():
                if not child.IsInner():
                    continue
                try:
                    aid_val = child.GetValue(maxon.Id(ASSET_ID_ATTR))
                    aid = str(aid_val[0]) if aid_val else ''
                    if asset_id in aid:
                        result.append(child)
                except (RuntimeError, TypeError, AttributeError, ValueError):
                    continue
        return result

    @staticmethod
    def find_node(graph, asset_id: 'str'):
        """Возвращает первый узел с данным asset ID или None."""
        result = JbBaseNodeMaterial.find_nodes_by_asset_id(graph, asset_id)
        return result[0] if result else None

    @staticmethod
    def add_node(graph, asset_id: 'str'):
        """Добавляет новый узел в граф."""
        return graph.AddChild(maxon.Id(), maxon.Id(asset_id))

    @staticmethod
    def find_or_add_node(graph, asset_id: 'str'):
        """Ищет узел, создаёт если не найден. Возвращает (node, was_created)."""
        node = JbBaseNodeMaterial.find_node(graph, asset_id)
        if node is not None:
            return (node, False)
        return (JbBaseNodeMaterial.add_node(graph, asset_id), True)

    @staticmethod
    def get_port(inputs, port_id: 'PortType'):
        """Возвращает входной порт узла.

        Стратегия:
        1. InternedId — Redshift (порты зарегистрированы в C4D-реестре).
        2. maxon.Id — Arnold и другие сторонние рендеры (оригинальный способ).
        3. Итерация GetChildren() — последний fallback по short ID.
        """
        if isinstance(port_id, int):
            children = inputs.GetChildren()
            return children[port_id] if port_id < len(children) else None
        try:
            port = inputs.FindChild(maxon.InternedId(port_id))
            if port and (not port.IsNullValue()):
                return port
        except (RuntimeError, TypeError, AttributeError):
            pass
        try:
            port = inputs.FindChild(maxon.Id(port_id))
            if port and (not port.IsNullValue()):
                return port
        except (RuntimeError, TypeError, AttributeError):
            pass
        short_id = port_id.rsplit('.', 1)[-1]
        for child in inputs.GetChildren():
            try:
                child_id = str(child.GetId())
                if child_id in (port_id, short_id):
                    return child
            except (RuntimeError, TypeError, AttributeError):
                continue
        return None

    @staticmethod
    def get_ports(inputs, port_ids: 'PortsType'):
        """Traverse node inputs by a chain of port IDs and return the final port."""
        current = inputs
        if isinstance(port_ids, PortType):
            port_ids = [port_ids]
        for port_id in port_ids:
            if current is None:
                return None
            current = JbBaseNodeMaterial.get_port(current, port_id)
            if current is None:
                return None
        return current

    @staticmethod
    def get_input_ports(node, port_ids: 'PortsType'):
        """Return the input port of a node by ID."""
        return JbBaseNodeMaterial.get_ports(node.GetInputs(), port_ids)

    @staticmethod
    def get_output_ports(node, port_ids: 'PortsType' = 0):
        """Return the output port of a node by ID."""
        return JbBaseNodeMaterial.get_ports(node.GetOutputs(), port_ids)

    def _disconnect_all(self, port) -> 'bool':
        """Disconnects all connections from the given port."""
        if port is None:
            return False
        if port.IsNullValue():
            return False
        port.RemoveConnections(maxon.PORT_DIR.INPUT, maxon.Wires.All())
        return True

    def _connect_port(self, out_port, node, port_ids: 'PortsType') -> 'bool':
        """Соединяет out_port с входным портом port_id узла node."""
        if out_port is None or node is None:
            return False
        inp = self.get_input_ports(node, port_ids)
        if inp is None:
            return False
        self._disconnect_all(inp)
        out_port.Connect(inp)
        return True

    def _wire_channel(self, channel: 'str', path: 'str') -> 'None':
        """Подключить канал к нужным портам материала."""
        method = getattr(self, f'_wire_{channel}', None)
        if method is not None:
            method(path)

    def apply_channel(self, material: 'c4d.BaseMaterial', channel: 'str', path: 'str'):
        """Apply a texture channel to the material."""
        nodespace = self.nodespace_id()
        if nodespace is None:
            node_material_logger.error('Node space ID is not defined for this material type.')
            return
        self._graph = self.ensure_graph(material, nodespace)
        if self._graph is None:
            node_material_logger.error('Material does not have the expected node space.')
            return
        with self._graph.BeginTransaction() as t:
            self._wire_channel(channel, path)
            t.Commit()
        material.Update(True, True)


# --- jiko_bridge_c4d.materials.jb_arnold_node_material ---

ARNOLD_NODESPACE = 'com.autodesk.arnold.nodespace'
ARNOLD_END = 'com.autodesk.arnold.material'
ARNOLD_STANDARD = 'com.autodesk.arnold.shader.standard_surface'
ARNOLD_IMAGE = 'com.autodesk.arnold.shader.image'
ARNOLD_COLCORRECT = 'com.autodesk.arnold.shader.color_correct'
ARNOLD_DISP = 'com.autodesk.arnold.shader.displacement'
ARNOLD_NORMALMAP = 'com.autodesk.arnold.shader.normal_map'
PORT_BASE_COLOR = f'{ARNOLD_STANDARD}.base_color'
PORT_NORMAL = f'{ARNOLD_STANDARD}.normal'
PORT_ROUGHNESS = f'{ARNOLD_STANDARD}.specular_roughness'
PORT_METALNESS = f'{ARNOLD_STANDARD}.metalness'
PORT_EMISSION = f'{ARNOLD_STANDARD}.emission'
PORT_EMIS_COLOR = f'{ARNOLD_STANDARD}.emission_color'
PORT_OPACITY = f'{ARNOLD_STANDARD}.opacity'
PORT_TRANSMISSION = f'{ARNOLD_STANDARD}.transmission'
PORT_TRANS_COLOR = f'{ARNOLD_STANDARD}.transmission_color'
PORT_SHADER_IN = f'{ARNOLD_END}.shader'
PORT_DISP_IN = f'{ARNOLD_END}.displacement'
PORT_CC_INPUT = f'{ARNOLD_COLCORRECT}.input'
PORT_CC_MULTIPLY = f'{ARNOLD_COLCORRECT}.multiply'
PORT_NM_INPUT = f'{ARNOLD_NORMALMAP}.input'
PORT_DISP_MAP = f'{ARNOLD_DISP}.normal_displacement_input'
PORT_IMG_FILE = f'{ARNOLD_IMAGE}.filename'


class JbArnoldNodeMaterial(JbBaseNodeMaterial):
    """Arnold node material implementation."""

    def nodespace_id(self) -> 'str':
        return ARNOLD_NODESPACE

    @property
    def _surface(self):
        surface, _ = self.find_or_add_node(self._graph, ARNOLD_STANDARD)
        self._connect_port(self.get_output_ports(surface), self._end, PORT_SHADER_IN)
        return surface

    @property
    def _end(self):
        return self.find_or_add_node(self._graph, ARNOLD_END)[0]

    def _make_image_node(self, channel: 'str', path: 'str'):
        node = self._make_labeled_node(self._graph, ARNOLD_IMAGE, channel)
        port = self.get_input_ports(node, PORT_IMG_FILE)
        if port is not None:
            port.SetDefaultValue(self.path_to_url(path))
        out = self.get_output_ports(node)
        return out

    def _wire_basecolor(self, path) -> 'None':
        img_out = self._make_image_node('basecolor', path)
        if img_out is None:
            return
        correct = self._make_labeled_node(self._graph, ARNOLD_COLCORRECT, 'basecolor_correct')
        self._connect_port(img_out, correct, PORT_CC_INPUT)
        self._connect_port(self.get_output_ports(correct), self._surface, PORT_BASE_COLOR)

    def _wire_normal(self, path) -> 'None':
        img_out = self._make_image_node('normal', path)
        if img_out is None:
            return
        nm, _ = self.find_or_add_node(self._graph, ARNOLD_NORMALMAP)
        self._connect_port(img_out, nm, PORT_NM_INPUT)
        nm_out = self.get_output_ports(nm)
        if nm_out is not None:
            self._connect_port(nm_out, self._surface, PORT_NORMAL)

    def _wire_roughness(self, path) -> 'None':
        img_out = self._make_image_node('roughness', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._surface, PORT_ROUGHNESS)

    def _wire_metallic(self, path) -> 'None':
        img_out = self._make_image_node('metallic', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._surface, PORT_METALNESS)

    def _wire_emissive(self, path) -> 'None':
        img_out = self._make_image_node('emissive', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._surface, PORT_EMIS_COLOR)
        p = self.get_port(self._surface, PORT_EMISSION)
        if p:
            p.SetDefaultValue(1.0)

    def _wire_opacity(self, path) -> 'None':
        img_out = self._make_image_node('opacity', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._surface, PORT_OPACITY)

    def _wire_refraction(self, path) -> 'None':
        img_out = self._make_image_node('refraction', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._surface, PORT_TRANS_COLOR)
        p = self.get_port(self._surface, PORT_TRANSMISSION)
        if p:
            p.SetDefaultValue(1.0)

    def _wire_height(self, path) -> 'None':
        img_out = self._make_image_node('height', path)
        if img_out is None:
            return
        disp, _ = self.find_or_add_node(self._graph, ARNOLD_DISP)
        self._connect_port(img_out, disp, PORT_DISP_MAP)
        disp_out = self.get_output_ports(disp)
        if disp_out is not None:
            self._connect_port(disp_out, self._end, PORT_DISP_IN)

    def _wire_ao(self, path) -> 'None':
        self._make_image_node('ao', path)


# --- jiko_bridge_c4d.materials.jb_redshift_node_material ---

RS_ID = 'com.redshift3d.redshift4c4d'
RS_NODESPACE = f'{RS_ID}.class.nodespace'
RS_CORE = f'{RS_ID}.nodes.core'
RS_OUTPUT = f'{RS_ID}.node.output'
RS_MATERIAL = f'{RS_CORE}.material'
RS_TEX = f'{RS_CORE}.texturesampler'
RS_BUMPMAP = f'{RS_CORE}.bumpmap'
RS_DISPLACEMENT = f'{RS_CORE}.displacement'
RS_PORT_SURFACE = f'{RS_OUTPUT}.surface'
RS_PORT_DIFFUSE = f'{RS_MATERIAL}.diffuse_color'
RS_PORT_BUMP = f'{RS_MATERIAL}.bump_input'
RS_PORT_ROUGHNESS = f'{RS_MATERIAL}.refl_roughness'
RS_PORT_EMISSIVE = f'{RS_MATERIAL}.emissive_color'
RS_PORT_METALNESS = f'{RS_MATERIAL}.refl_metalness'
RS_PORT_DISP_OUT = f'{RS_OUTPUT}.displacement'
RS_PORT_DISP_TEX = f'{RS_DISPLACEMENT}.texmap'
RS_PORT_BUMP_IN = f'{RS_BUMPMAP}.input'
RS_PORT_TEX_FILE = f'{RS_TEX}.tex0'
RS_PORT_TEX_PATH_SUB = 'path'


class JbRedshiftNodeMaterial(JbBaseNodeMaterial):
    """Redshift for C4D — node material."""

    def nodespace_id(self) -> 'str':
        return RS_NODESPACE

    @property
    def _material(self):
        node, _ = self.find_or_add_node(self._graph, RS_MATERIAL)
        self._connect_port(self.get_output_ports(node), self._output, RS_PORT_SURFACE)
        return node

    @property
    def _output(self):
        return self.find_or_add_node(self._graph, RS_OUTPUT)[0]

    def _make_texture_node(self, channel: 'str', path: 'str'):
        node = self._make_labeled_node(self._graph, RS_TEX, channel)
        port = self.get_input_ports(node, [RS_PORT_TEX_FILE, RS_PORT_TEX_PATH_SUB])
        if port is not None:
            port.SetDefaultValue(self.path_to_url(path))
        out = self.get_output_ports(node)
        return out

    def _wire_basecolor(self, path) -> 'None':
        tex_out = self._make_texture_node('basecolor', path)
        if tex_out is None:
            return
        self._connect_port(tex_out, self._material, RS_PORT_DIFFUSE)

    def _wire_normal(self, path) -> 'None':
        tex_out = self._make_texture_node('normal', path)
        if tex_out is None:
            return
        bump, _ = self.find_or_add_node(self._graph, RS_BUMPMAP)
        self._connect_port(tex_out, bump, RS_PORT_BUMP_IN)
        bump_out = self.get_output_ports(bump)
        if bump_out is not None:
            self._connect_port(bump_out, self._material, RS_PORT_BUMP)

    def _wire_roughness(self, path) -> 'None':
        tex_out = self._make_texture_node('roughness', path)
        if tex_out is None:
            return
        self._connect_port(tex_out, self._material, RS_PORT_ROUGHNESS)

    def _wire_metallic(self, path) -> 'None':
        tex_out = self._make_texture_node('metallic', path)
        if tex_out is None:
            return
        self._connect_port(tex_out, self._material, RS_PORT_METALNESS)

    def _wire_emissive(self, path) -> 'None':
        tex_out = self._make_texture_node('emissive', path)
        if tex_out is None:
            return
        self._connect_port(tex_out, self._material, RS_PORT_EMISSIVE)

    def _wire_height(self, path) -> 'None':
        tex_out = self._make_texture_node('height', path)
        if tex_out is None:
            return
        disp, _ = self.find_or_add_node(self._graph, RS_DISPLACEMENT)
        self._connect_port(tex_out, disp, RS_PORT_DISP_TEX)
        disp_out = self.get_output_ports(disp)
        if disp_out is not None:
            self._connect_port(disp_out, self._output, RS_PORT_DISP_OUT)


# --- jiko_bridge_c4d.materials.jb_standard_node_material ---

C4D_NODESPACE = 'net.maxon.nodespace.standard'
C4D_BSDF = 'net.maxon.render.node.bsdf'
C4D_IMAGE = 'net.maxon.pattern.node.generator.image'
C4D_END = 'net.maxon.render.node.material'
PORT_BSDF_COLOR = 'color'
PORT_BSDF_ROUGHNESS = 'roughness'
PORT_BSDF_NORMAL = 'normal'
PORT_BSDF_METALNESS = 'reflectionstrength'
PORT_MAT_EMISSION = 'emission'
PORT_MAT_ALPHA = 'alpha'
PORT_MAT_DISPLACEMENT = 'displacement'
PORT_MAT_TRANSPARENCY = 'transparency'
PORT_MAT_BSDFLAYERS = 'bsdflayers'
PORT_MAT_BSDFLAYER = 'bsdflayer'
PORT_IMG_URL = 'url'
PORT_IMG_RESULT = 'result'


class JbStandardNodeMaterial(JbBaseNodeMaterial):
    """C4D Native Standard Renderer — node material."""

    def nodespace_id(self) -> 'str':
        return C4D_NODESPACE

    @property
    def _bsdf(self):
        bsdf, _ = self.find_or_add_node(self._graph, C4D_BSDF)
        self._connect_port(
            self.get_output_ports(bsdf), self._end, [PORT_MAT_BSDFLAYERS, 0, PORT_MAT_BSDFLAYER]
        )
        return bsdf

    @property
    def _end(self):
        end, _ = self.find_or_add_node(self._graph, C4D_END)
        return end

    def _make_image_node(self, channel: 'str', path: 'str'):
        node = self._make_labeled_node(self._graph, C4D_IMAGE, channel)
        port = self.get_input_ports(node, PORT_IMG_URL)
        if port is not None and (not port.IsNullValue()):
            port.SetDefaultValue(self.path_to_url(path))
        out = self.get_output_ports(node, PORT_IMG_RESULT)
        return out

    def _wire_basecolor(self, path) -> 'None':
        img_out = self._make_image_node('basecolor', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._bsdf, PORT_BSDF_COLOR)

    def _wire_roughness(self, path) -> 'None':
        img_out = self._make_image_node('roughness', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._bsdf, PORT_BSDF_ROUGHNESS)

    def _wire_normal(self, path) -> 'None':
        img_out = self._make_image_node('normal', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._bsdf, PORT_BSDF_NORMAL)

    def _wire_emissive(self, path) -> 'None':
        img_out = self._make_image_node('emissive', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._end, PORT_MAT_EMISSION)

    def _wire_opacity(self, path) -> 'None':
        img_out = self._make_image_node('opacity', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._end, PORT_MAT_ALPHA)

    def _wire_height(self, path) -> 'None':
        img_out = self._make_image_node('height', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._end, PORT_MAT_DISPLACEMENT)

    def _wire_refraction(self, path) -> 'None':
        img_out = self._make_image_node('refraction', path)
        if img_out is None:
            return
        self._connect_port(img_out, self._end, PORT_MAT_TRANSPARENCY)


# --- jiko_bridge_c4d.materials ---


# --- jiko_bridge_c4d.materials.jb_material_importer ---

ARNOLD_ID = 1029988
REDSHIFT_ID = c4d.VPrsrenderer
VIEWPORT_ID = 300001061
material_import_logger = get_logger('jiko_bridge_c4d.materials.jb_material_importer')


class JbMaterialImporter(JbMaterialImporterBase):
    """Material importer that handles different renderers."""

    def __init__(self, source: JbSource):
        self._redshift = JbRedshiftNodeMaterial()
        self._arnold = JbArnoldNodeMaterial()
        self._standard = JbStandardNodeMaterial()
        self._source = source

    @property
    def source(self) -> JbSource:
        """Return the active document."""
        return self._source or c4d.documents.GetActiveDocument()

    def find_existing(self, name: str):
        """Find an existing material by name."""
        mat = self.source.GetFirstMaterial()
        while mat:
            if mat.GetName() == name:
                return mat
            mat = mat.GetNext()
        return None

    def get_material_name(self, material: c4d.BaseMaterial) -> str | None:
        """Return the material name, or None without a material."""
        return material.GetName() if material else None

    def set_material_name(self, material: c4d.BaseMaterial, name: str):
        """Rename the material in place."""
        if material:
            material.SetName(name)

    def _get_material_renderer(self):
        render_id = self.source.GetActiveRenderData()[c4d.RDATA_RENDERENGINE]
        if render_id == REDSHIFT_ID:
            return self._redshift
        if render_id == ARNOLD_ID:
            return self._arnold
        if render_id == VIEWPORT_ID:
            return self._standard
        return self._standard

    def import_material(self, asset: AssetModel, file: AssetFile) -> Optional[c4d.BaseMaterial]:
        """Import a single material file into the scene."""
        if file.asset_type is None or file.filepath is None:
            material_import_logger.error('Material file is missing type or path')
            return None
        renderer = self._get_material_renderer()
        channel = file.asset_type.lower()
        path = file.filepath
        material_name = f'{asset.pack_name}__{asset.asset_name}'
        material = self.find_existing(material_name)
        if not material:
            material = c4d.BaseMaterial(c4d.Mmaterial)
            material.SetName(material_name)
            self.source.InsertMaterial(material)
        renderer.apply_channel(material, channel, path)
        c4d.EventAdd()
        return material


# --- jiko_bridge_c4d.jb_asset_importer ---

asset_import_logger = get_logger('jiko_bridge_c4d.jb_asset_importer')


class JbAssetImporter(JbAssetImporterBase):
    """Handles importing assets from Jiko Bridge into scene."""

    def __init__(self, source: JbSource):
        self.api = JbAPI()
        self.scene = JbScene(source)
        self.materials = JbMaterialImporter(source)
        self._asset_cache: dict[str, AssetModel | None] = {}

    def import_assets(self):
        assets = self._collect_assets()
        for asset in assets:
            self._import_single(asset)

    def import_message(self) -> str:
        materials, containers = self._collect_data()
        if materials:
            return f'Import assets for materials?\n{len(materials)} material(s) with asset info found in selection.'
        if containers:
            return f'Import assets for asset containers?\n{len(containers)} asset container(s) found in selection.'
        return 'Import active asset from Jiko Bridge.'

    def _collect_data(self) -> tuple[list[JbMaterial], list[JbContainer]]:
        objects = self.scene.get_selection()
        materials = self.scene.get_materials_from_objects(objects)
        containers = self.scene.get_containers_from_objects(objects)
        return (materials, containers)

    def _collect_assets(self) -> list[AssetModel]:
        assets: list[AssetModel] = []
        materials, containers = self._collect_data()
        if materials:
            for mat in materials:
                mat_name = self.materials.get_material_name(mat)
                if not mat_name:
                    continue
                asset_model = AssetModel.from_string(mat_name)
                if asset_model:
                    asset = self.api.get_asset(asset_model)
                    if asset:
                        assets.append(asset)
                else:
                    asset = self.api.get_asset_by_search(mat_name)
                    if asset:
                        assets.append(asset)
                        self.materials.set_material_name(
                            mat, f'{asset.pack_name}__{asset.asset_name}'
                        )
        elif containers:
            for container in containers:
                self.scene.clear_container(container)
                asset_model = self.scene.get_asset_data_from_container(container)
                if not asset_model:
                    continue
                asset_model.active_type = None
                asset = self.api.get_asset(asset_model)
                if asset:
                    assets.append(asset)
        else:
            asset = self.api.get_active_asset()
            if asset:
                assets.append(asset)
        return list(assets)

    def _import_single(self, asset: AssetModel) -> None:
        for file in asset.files:
            match file.bridge_type:
                case 'model':
                    container = self._create_model(asset, file)
                    self._convert_to_instances(container)
                case 'material':
                    mat = self.materials.import_material(asset, file)
                    if mat:
                        self.scene.merge_duplicates_materials(mat)
                case _:
                    asset_import_logger.warning('Unsupported bridge type: %s', file.bridge_type)

    def _create_model(self, asset, file):
        container, exists = self.scene.get_or_create_asset_container(asset, file)
        if exists:
            self.scene.create_instance(container, asset.asset_name)
        else:
            self.scene.import_with_temp(file.filepath, container)
        return container

    def _convert_to_instances(self, container) -> None:
        queue = [container]
        self._asset_cache = {}
        visited = set()
        while queue:
            current = queue.pop(0)
            if id(current) in visited:
                continue
            visited.add(id(current))
            objects = self.scene.walk([current])
            for obj in objects:
                asset_model = self._resolve_asset_from_object(obj)
                if asset_model and (
                    asset_container := self._resolve_placeholder(obj, current, asset_model)
                ):
                    queue.append(asset_container)
            self.scene.cleanup_container(current)

    def _resolve_asset_from_object(self, obj) -> AssetModel | None:
        names = self.scene.get_names_from_placeholder(obj)
        for name in names:
            if cached := self._asset_cache.get(name):
                return cached
            raw_asset = AssetModel.from_string(name)
            if raw_asset:
                asset = self.api.get_asset(raw_asset)
            else:
                asset = self.api.get_asset_by_search(name)
            self._asset_cache[name] = asset
            if asset:
                return asset
        return None

    def _resolve_placeholder(self, obj, container, asset_model) -> JbContainer | None:
        asset_container = self.scene.get_container(asset_model)
        new_container = None
        if not asset_container:
            for file in asset_model.files:
                asset_container, exists = self.scene.get_or_create_asset_container(
                    asset_model, file
                )
                if not exists:
                    self.scene.import_with_temp(file.filepath, asset_container)
            new_container = asset_container
        instance = self.scene.create_instance(asset_container, asset_model.asset_name)
        self.scene.copy_object_transform(instance, obj)
        self.scene.move_objects_to_container([instance], container)
        self.scene.remove_object(obj)
        return new_container


# --- jiko_bridge_c4d.jb_commands ---

IDC_POPUP_ACTION_IMPORT = 2001
IDC_POPUP_ACTION_EXPORT = 2002
IDC_POPUP_ACTION_SOLO = 2003
IDC_POPUP_ACTION_SETTINGS = 2005


class JbCommandsPopup:
    """icon reference:
    https://developers.maxon.net/docs/py/2024_3_0/modules/c4d.bitmaps/RESOURCEIMAGE.html
    """

    def __init__(self, source: JbSource):
        self.doc = source
        self.scene = JbScene(source)
        self.asset_import = JbAssetImporter(source)
        self.asset_export = JbAssetExporter(source)
        self._settings_dialog = JbSettingsDialog(source)

    def export_asset(self):
        """Export asset to Jiko Bridge."""
        self.doc.StartUndo()
        try:
            msg = self.asset_export.export_message()
            if c4d.gui.QuestionDialog(msg):
                self.asset_export.export_asset()
        finally:
            self.doc.EndUndo()
            c4d.EventAdd()

    def import_asset(self):
        """Import asset from Jiko Bridge."""
        self.doc.StartUndo()
        try:
            msg = self.asset_import.import_message()
            if c4d.gui.QuestionDialog(msg):
                self.asset_import.import_assets()
        finally:
            self.doc.EndUndo()
            c4d.EventAdd()

    def solo(self):
        """Solo mode with history"""
        self.doc.StartUndo()
        try:
            self.scene.solo()
        finally:
            self.doc.EndUndo()
            c4d.EventAdd()

    def open_settings(self):
        """Открыть диалог настроек."""
        self._settings_dialog.Open(dlgtype=c4d.DLG_TYPE_MODAL, defaultw=250, defaulth=120)

    def show_popup_menu(self):
        """Show the popup menu."""
        bc = c4d.BaseContainer()
        bc.InsData(IDC_POPUP_ACTION_IMPORT, f'Import&i{c4d.ID_MODELING_FLATTEN_TOOL}&')
        bc.InsData(IDC_POPUP_ACTION_EXPORT, f'Export&i{c4d.ID_GLOBALMACHINELIST}&')
        bc.InsData(IDC_POPUP_ACTION_SOLO, f'Solo&i{c4d.RESOURCEIMAGE_EYEACTIVE}&')
        bc.InsData(0, '')
        bc.InsData(IDC_POPUP_ACTION_SETTINGS, f'Settings&i{c4d.RESOURCEIMAGE_PIN}&')
        res = c4d.gui.ShowPopupDialog(cd=None, bc=bc, x=c4d.MOUSEPOS, y=c4d.MOUSEPOS)
        if res == IDC_POPUP_ACTION_IMPORT:
            self.import_asset()
        elif res == IDC_POPUP_ACTION_EXPORT:
            self.export_asset()
        elif res == IDC_POPUP_ACTION_SOLO:
            self.solo()
        elif res == IDC_POPUP_ACTION_SETTINGS:
            self.open_settings()


class JbCommands:
    """Main command for headless execution."""

    def __init__(self, source: JbSource):
        self.asset_import = JbAssetImporter(source)
        self.asset_export = JbAssetExporter(source)

    def export_asset(self) -> None:
        """Export asset to Jiko Bridge."""
        return self.asset_export.export_asset()

    def import_asset(self) -> None:
        """Import asset from Jiko Bridge."""
        return self.asset_import.import_assets()


# --- jiko_bridge_c4d.jb_plugin ---

JIKO_BRIDGE_ID = 1096086
JIKO_BRIDGE_NAME = 'Jiko Bridge'
JIKO_BRIDGE_HELP = 'Jiko Bridge help to improve your workflow'


class JikoBridge(c4d.plugins.CommandData):
    """Main command plugin class for Jiko Bridge."""

    def GetScriptName(self):
        """Return a stable script name."""
        return JIKO_BRIDGE_NAME

    def Execute(self, doc):
        """Show the Jiko Bridge commands popup menu."""
        JbCommandsPopup(doc).show_popup_menu()
        return True


def registerJikoBridge() -> None:
    """Register the stable command plugin once in Cinema 4D.

    Called once by the ``jiko_bridge_c4d.pyp`` entry point on plugin load.
    """
    if c4d.plugins.FindPlugin(JIKO_BRIDGE_ID, c4d.PLUGINTYPE_COMMAND):
        return
    try:
        c4d.plugins.RegisterCommandPlugin(
            id=JIKO_BRIDGE_ID,
            str=JIKO_BRIDGE_NAME,
            info=0,
            help=JIKO_BRIDGE_HELP,
            dat=JikoBridge(),
            icon=None,
        )
    except (TypeError, RuntimeError, ValueError) as e:
        print(f'Failed to register Jiko Bridge plugin: {e}')


# --- jiko_bridge_c4d.jb_utils ---


def is_headless() -> bool:
    """Headless-режим: c4dpy или Cinema 4D Commandline."""
    executable = sys.argv[0].lower() if sys.argv else ''
    return 'c4dpy' in executable


@contextmanager
def busy_cursor(status_text: str = ''):
    """Context manager to show a busy cursor with optional status text."""
    if status_text:
        c4d.StatusSetText(status_text)
    c4d.gui.SetMousePointer(c4d.MOUSE_BUSY)
    try:
        yield
    finally:
        c4d.gui.SetMousePointer(c4d.MOUSE_NORMAL)
        c4d.StatusClear()


def load_arnold_module():
    """Load Arnold module if it exists in the Cinema 4D library path."""
    try:
        arnold_folder = os.path.join(c4d.storage.GeGetC4DPath(c4d.C4D_PATH_LIBRARY), 'scripts')
        if os.path.exists(arnold_folder) and arnold_folder not in sys.path:
            sys.path.append(arnold_folder)
    except OSError as e:
        print(f'Failed to load Arnold module: {e}')


# --- jiko_bridge_c4d ---


# --- jiko_bridge_c4d.scene ---


# --- entry.py ---

if __name__ == '__main__':
    registerJikoBridge()
