# Generated by jiko-bundler. Edit the source files, not this bundle.

import json
import logging
import os
import platform
import re
import tempfile
import urllib.error
import urllib.request
import uuid
from abc import ABC, abstractmethod
from collections import defaultdict
from contextlib import contextmanager
from dataclasses import dataclass, field
from logging import Logger
from pathlib import Path
from typing import Any, Dict, Generator, Generic, List, Optional, TypeAlias, TypedDict, TypeVar

import bmesh
import bpy
import mathutils

# --- jiko_bridge_blend ---


# --- jiko_bridge_client.models ---

# Data models shared by every Jiko Bridge integration.
# Code by Semyon Shapoval, 2026


@dataclass
class AssetFile:
    """Represents a file associated with an asset."""

    filepath: Optional[str] = None
    asset_type: Optional[str] = None
    bridge_type: Optional[str] = None

    @classmethod
    def from_dict(cls, data: dict) -> 'AssetFile':
        """Create an AssetFile instance from a dictionary."""
        return cls(
            filepath=data.get('filepath', None),
            asset_type=data.get('assetType', None),
            bridge_type=data.get('bridgeType', None),
        )

    def to_dict(self) -> dict:
        """Convert the AssetFile instance to a dictionary."""
        result: Dict[str, Any] = {}
        if self.filepath:
            result['filepath'] = self.filepath
        if self.asset_type:
            result['assetType'] = self.asset_type
        if self.bridge_type:
            result['bridgeType'] = self.bridge_type
        return result


@dataclass
class AssetModel:
    """Represents a complete asset with its metadata and associated files."""

    vault_name: Optional[str] = None
    pack_name: Optional[str] = None
    asset_name: Optional[str] = None
    active_type: Optional[str] = None
    files: List[AssetFile] = field(default_factory=list)

    def __hash__(self) -> int:
        return hash((self.vault_name, self.pack_name, self.asset_name))

    @classmethod
    def from_string(cls, value: str) -> Optional['AssetModel']:
        """Parse packName / assetName from a placeholder object/tag name."""
        normalized = re.sub('\\.\\d+$', '', value)
        pattern = re.compile('(?P<pack>.+?)__(?P<asset>.+?)$')
        m = pattern.match(normalized)
        if m:
            return cls(pack_name=m.group('pack'), asset_name=m.group('asset'))
        return None

    @classmethod
    def from_dict(cls, data: dict) -> 'AssetModel':
        """Create an AssetModel instance from a dictionary."""
        return cls(
            vault_name=data.get('vaultName'),
            pack_name=data.get('packName'),
            asset_name=data.get('assetName'),
            files=[AssetFile.from_dict(f) for f in data.get('files', [])],
        )

    def to_dict(self) -> dict:
        """Convert the AssetModel instance to a dictionary."""
        result: Dict[str, Any] = {}
        files = list(self.files)
        if self.active_type:
            files.append(AssetFile(asset_type=self.active_type))
        if self.vault_name:
            result['vaultName'] = self.vault_name
        if self.pack_name:
            result['packName'] = self.pack_name
        if self.asset_name:
            result['assetName'] = self.asset_name
        if files:
            result['files'] = [f.to_dict() for f in files]
        return result


class JbPlaceholderInfo(TypedDict):
    """Represents information about a placeholder object."""

    asset: AssetModel
    transform: Any


# --- jiko_bridge_client.contracts ---

JbSourceT = TypeVar('JbSourceT')
JbMatrixT = TypeVar('JbMatrixT')
JbContainerT = TypeVar('JbContainerT')
JbObjectT = TypeVar('JbObjectT')
JbMaterialT = TypeVar('JbMaterialT')


class JbSceneABC(ABC, Generic[JbSourceT, JbMatrixT, JbContainerT, JbObjectT, JbMaterialT]):
    """Abstract base class for all Jiko Bridge scene operations."""

    @abstractmethod
    def __init__(self, source: JbSourceT): ...

    @property
    @abstractmethod
    def source(self) -> JbSourceT:
        """Return the source scene."""

    @property
    @abstractmethod
    def logger(self) -> Logger:
        """Return the logger instance."""

    @abstractmethod
    def walk(
        self, root: list[JbObjectT | JbContainerT | JbMaterialT]
    ) -> list[JbObjectT | JbContainerT | JbMaterialT]:
        """Call *fn* for every object in the root hierarchy (pre-order)."""

    @abstractmethod
    def get_materials_from_objects(self, objects: list[JbObjectT]) -> list[JbMaterialT]:
        """Return materials used by the given objects."""

    @abstractmethod
    def get_selection(self) -> list[JbObjectT | JbContainerT | JbMaterialT]:
        """Return the currently selected objects or materials."""

    @abstractmethod
    def copy_object_transform(self, obj: JbObjectT, target_obj: JbObjectT) -> None:
        """Set the transform of the given object."""

    @abstractmethod
    def remove_object(self, obj: JbObjectT) -> None:
        """Remove the given object from the scene."""

    @abstractmethod
    def get_depth(self, obj: JbObjectT | JbContainerT | JbMaterialT) -> int:
        """Return the depth of the given object in the hierarchy."""

    @abstractmethod
    def merge_duplicates_materials(self, material: JbMaterialT) -> None:
        """Replace duplicate materials (.001, .002, ...) with the given base material."""

    @abstractmethod
    def get_container(self, asset: AssetModel) -> Optional[JbContainerT]:
        """Get the container associated with the given asset, if it exists."""

    @abstractmethod
    def get_or_create_container(
        self, name: str, parent: Optional[JbContainerT] = None
    ) -> JbContainerT:
        """Get or create a container with the given name under the parent."""

    @abstractmethod
    def get_or_create_asset_container(
        self, asset: AssetModel, file: Optional[AssetFile] = None
    ) -> tuple[JbContainerT, bool]:
        """Get or create a container with asset data."""

    @abstractmethod
    def set_asset_data(
        self, container: JbContainerT, asset: AssetModel, file: Optional[AssetFile] = None
    ) -> None:
        """Store asset info in the container's custom properties."""

    @abstractmethod
    def get_asset_data_from_container(self, container: JbContainerT) -> Optional[AssetModel]:
        """Parse asset info from a container's custom properties."""

    @abstractmethod
    def copy_asset_data(self, src: JbContainerT, dst: JbContainerT | JbObjectT) -> None:
        """Copy custom properties from src to dst."""

    @abstractmethod
    def get_containers_from_objects(self, objects: list[JbObjectT]) -> list[JbContainerT]:
        """Return asset containers found among the given objects (via instance Empties)."""

    @abstractmethod
    def get_containers_from_instances(self, objects: list[JbObjectT]) -> list[JbContainerT]:
        """Return asset containers found among the given instances."""

    @abstractmethod
    def move_objects_to_container(self, objects: list[JbObjectT], container: JbContainerT) -> None:
        """Move objects into target collection."""

    @abstractmethod
    def cleanup_container(self, container: JbContainerT) -> None:
        """Remove empty objects that have no children and no data."""

    @abstractmethod
    def clear_container(self, container: JbContainerT) -> None:
        """Remove all objects from the container."""

    @abstractmethod
    def get_children(self, obj: JbObjectT | JbContainerT) -> list[JbObjectT | JbContainerT]:
        """Return the children of the given object or container."""

    @abstractmethod
    def create_instance(self, container: JbContainerT, name: str) -> JbObjectT:
        """Create an instance of the given object."""

    @abstractmethod
    def get_names_from_placeholder(self, obj: JbObjectT) -> List[str]:
        """Extract placeholder info from objects and remove them."""

    @abstractmethod
    def replace_instances_with_placeholders(
        self, objects: list[JbObjectT], source: JbSourceT
    ) -> list[JbObjectT]:
        """Replace instances in the list with placeholders."""

    @abstractmethod
    def create_placeholder(
        self, asset_model: AssetModel, transform: JbMatrixT, source: JbSourceT
    ) -> JbObjectT:
        """Create a placeholder object in the scene based on the info."""

    @abstractmethod
    def import_file(self, file_path: str) -> bool:
        """Import a file into the active scene."""

    @abstractmethod
    def _import_fbx(self, file_path: str) -> bool: ...

    @abstractmethod
    def export_file(self, ext: str) -> Optional[str]:
        """Export the active scene to a file and return its path."""

    @abstractmethod
    def _export_fbx(self, file_path: str) -> Optional[str]: ...

    @abstractmethod
    def temp_source(
        self,
        objects: Optional[list[JbObjectT | JbContainerT]] = None,
        unit_scale: float | int = 1.0,
        debug: bool = False,
    ) -> Generator[JbSourceT, None, None]:
        """Context manager for temporary scenes."""

    @abstractmethod
    def import_with_temp(self, file_path: str, target: JbContainerT) -> None:
        """Import a file into an isolated scene, then copy to target collection."""

    @abstractmethod
    def export_with_temp(self, src: list[JbObjectT | JbContainerT], ext: str) -> Optional[str]:
        """Copy objects to isolated scene, replace instances, export."""

    @abstractmethod
    def get_project_filepath(self) -> Optional[str]:
        """Return the current project filepath, if it exists."""

    @abstractmethod
    def solo(self):
        """Solo mode with history"""


class JbMaterialImporterABC(ABC, Generic[JbMaterialT]):
    """Abstract base class for Material Importers."""

    @abstractmethod
    def get_material_name(self, material: JbMaterialT) -> str | None:
        """Get the name of a material."""

    @abstractmethod
    def set_material_name(self, material: JbMaterialT, name: str):
        """Set the name of a material."""

    @abstractmethod
    def import_material(self, asset: AssetModel, file: AssetFile) -> Optional[JbMaterialT]:
        """Import a single material file into the scene."""


class JbSettingsABC(ABC, Generic[JbContainerT]):
    """Abstract base class for per-scene settings storage."""

    @abstractmethod
    def get_export_format(self) -> str:
        """Return the current export format (e.g. 'fbx', 'abc')."""

    @abstractmethod
    def load_solo_stack(self) -> list[list]:
        """Return the full solo-mode history as a list of container lists."""

    @abstractmethod
    def save_solo_selection(self, containers: list[JbContainerT]) -> None:
        """Push a new solo selection onto the history stack.

        No-op if the selection is identical to the most recent entry.
        """

    @abstractmethod
    def pop_solo_selection(self) -> list:
        """Remove the current selection and return the previous one.

        Returns an empty list if there is no previous entry.
        """


class JbAssetImporterABC(ABC, Generic[JbContainerT, JbObjectT, JbMaterialT]):
    """Abstract base class for Asset Importers.

    The source document is taken by ``__init__`` and is deliberately not part of
    the contract: it describes the interface of an instance, not how it is built.
    """

    @abstractmethod
    def import_assets(self) -> None:
        """Imports assets by selection."""

    @abstractmethod
    def import_message(self) -> str:
        """Return a confirmation message based on the current selection."""

    @abstractmethod
    def _collect_data(self) -> tuple[list[JbMaterialT], list[JbContainerT]]: ...

    @abstractmethod
    def _collect_assets(self) -> list[AssetModel]: ...

    @abstractmethod
    def _import_single(self, asset: AssetModel) -> None: ...

    @abstractmethod
    def _create_model(self, asset: AssetModel, file: AssetFile) -> JbContainerT: ...

    @abstractmethod
    def _convert_to_instances(self, container: JbContainerT) -> None: ...

    @abstractmethod
    def _resolve_placeholder(
        self, obj: JbObjectT, container: JbContainerT, asset_model: AssetModel
    ) -> JbContainerT | None: ...


class JbAssetExporterABC(ABC, Generic[JbContainerT, JbObjectT, JbMaterialT]):
    """Abstract base class for Asset Exporters.

    As in the importer contract, the source document is constructor-only and is
    therefore not part of the interface.
    """

    @abstractmethod
    def export_asset(self) -> None:
        """Exports an asset from the scene into Jiko Bridge."""

    @abstractmethod
    def export_message(self) -> str:
        """Return a confirmation message based on the current selection and asset containers."""

    @abstractmethod
    def _collect_data(
        self,
    ) -> tuple[list[JbContainerT | JbObjectT | JbMaterialT], list[JbContainerT]]: ...

    @abstractmethod
    def _update_asset(self, container: JbContainerT) -> None: ...

    @abstractmethod
    def _create_new_asset(self, objects: list[JbObjectT]) -> None: ...


class JbAPIABC(ABC):
    """Abstract base class for Jiko Bridge API interactions."""

    @abstractmethod
    def get_active_asset(self) -> Optional[AssetModel]:
        """Get the currently active asset based on selection or context."""

    @abstractmethod
    def get_asset_by_search(self, search_key: str) -> Optional[AssetModel]:
        """Search for an Asset by a free-form key."""

    @abstractmethod
    def get_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        """Get Asset by an AssetModel object."""

    @abstractmethod
    def create_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        """Create a new Asset with the given files and optional metadata."""

    @abstractmethod
    def update_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        """Update an existing Asset's files and metadata."""


# --- jiko_bridge_client.logger ---

JB_ENV = os.getenv('JB_ENV', 'production')
_DEFAULT_LEVEL = logging.INFO if JB_ENV == 'production' else logging.DEBUG


def get_logger(name: str, level: int | None = None) -> logging.Logger:
    """Return a logger with a single console handler.

    Calling this twice for the same name returns the already configured
    logger untouched, so imports are safe.
    """
    logger = logging.getLogger(name)
    if logger.handlers:
        return logger
    logger.setLevel(level if level is not None else _DEFAULT_LEVEL)
    formatter = logging.Formatter(
        '[Jiko Bridge] %(levelname)s [%(name)s] %(message)s', datefmt='%H:%M:%S'
    )
    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG)
    console.setFormatter(formatter)
    logger.addHandler(console)
    logger.propagate = False
    return logger


def _pretty(value: Any) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False)


def _error_body(error: BaseException) -> str:
    """Best-effort read of an HTTP error response body."""
    try:
        return getattr(error, 'read')().decode(errors='replace').strip() or '-'
    except (AttributeError, OSError):
        return '-'


def log_http(
    logger: logging.Logger,
    method: str,
    endpoint: str,
    payload: Optional[dict] = None,
    response: Optional[dict] = None,
    error: Optional[BaseException] = None,
) -> None:
    """Log one HTTP exchange: what was sent, then the reply or the failure."""
    sent = f'{method} {endpoint}'
    if payload is not None:
        sent += '\n' + _pretty(payload)
    if error is None:
        logger.debug('API response: %s\n%s', sent, _pretty(response))
    elif isinstance(error, urllib.error.HTTPError) and error.code == 404:
        logger.debug('JB_API not found: %s %s\nRequest: %s', error.code, error.reason, sent)
    elif isinstance(error, urllib.error.HTTPError):
        logger.error(
            'JB_API HTTP error: %s %s\nRequest: %s\nResponse: %s',
            error.code,
            error.reason,
            sent,
            _error_body(error),
        )
    else:
        logger.exception('JB_API error: %s\nRequest: %s', error, sent)


# --- jiko_bridge_client.api ---

DEFAULT_PORT = 5174
logger = get_logger('jiko_bridge_client.api')


def _get_port() -> int:
    """Read the API port from the Jiko Bridge desktop app settings.

    Falls back to DEFAULT_PORT when the settings file is missing or
    unreadable, so the client always has a usable address.
    """
    system = platform.system()
    if system == 'Windows':
        path = os.path.join(os.getenv('APPDATA', ''), 'jiko-bridge', 'settings.json')
    elif system == 'Darwin':
        path = os.path.expanduser('~/Library/Application Support/jiko-bridge/settings.json')
    else:
        base = os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
        path = os.path.join(base, 'jiko-bridge', 'settings.json')
    try:
        with open(path, 'r', encoding='utf-8') as f:
            port = json.load(f).get('apiPort')
        if isinstance(port, int):
            return port
    except (OSError, json.JSONDecodeError):
        pass
    return DEFAULT_PORT


class JbAPI(JbAPIABC):
    """Client for communicating with the Jiko Bridge API server."""

    def __init__(self, host: str = 'localhost', port: Optional[int] = None):
        self.base_url = f'http://{host}:{port or _get_port()}'

    def _request(
        self, endpoint: str, payload: Optional[dict] = None, method: str = 'GET', timeout: int = 15
    ) -> Optional[dict]:
        data = json.dumps(payload).encode() if payload is not None else None
        headers = {'Content-Type': 'application/json'} if data else {}
        req = urllib.request.Request(
            f'{self.base_url}{endpoint}', data=data, headers=headers, method=method
        )
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                parsed = json.loads(resp.read().decode())
        except (urllib.error.URLError, json.JSONDecodeError, OSError) as e:
            log_http(logger, method, endpoint, payload, error=e)
            return None
        log_http(logger, method, endpoint, payload, response=parsed)
        return parsed

    def _asset(
        self, endpoint: str, payload: Optional[dict] = None, method: str = 'GET', timeout: int = 15
    ) -> Optional[AssetModel]:
        """Query an asset endpoint and decode the reply into an asset."""
        data = (self._request(endpoint, payload, method, timeout) or {}).get('data')
        return AssetModel.from_dict(data) if data else None

    def get_active_asset(self) -> Optional[AssetModel]:
        return self._asset('/api/asset/active')

    def get_asset_by_search(self, search_key: str) -> Optional[AssetModel]:
        return self._asset('/api/asset', {'searchKey': search_key}, 'POST')

    def get_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        return self._asset('/api/asset', asset.to_dict(), 'POST')

    def create_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        return self._asset('/api/asset/create', asset.to_dict(), 'POST', 300)

    def update_asset(self, asset: AssetModel) -> Optional[AssetModel]:
        return self._asset('/api/asset/update', asset.to_dict(), 'POST', 30)


# --- jiko_bridge_client ---

# Jiko Bridge client.
#
# Shared models, HTTP API client and integration contracts used by every
# Jiko Bridge DCC plugin (Blender, Cinema 4D, Maya, Houdini).
#
#     from jiko_bridge_client import JbAPI, AssetModel, AssetFile
#
# Code by Semyon Shapoval, 2026


# --- jiko_bridge_blend.jb_types ---

JbSource: TypeAlias = bpy.types.Context
JbMatrix: TypeAlias = mathutils.Matrix
JbContainer: TypeAlias = bpy.types.Collection
JbObject: TypeAlias = bpy.types.Object
JbMaterial: TypeAlias = bpy.types.Material
JbData: TypeAlias = JbContainer | JbObject | JbMaterial
JbSceneBase: TypeAlias = JbSceneABC[JbSource, JbMatrix, JbContainer, JbObject, JbMaterial]
JbMaterialImporterBase: TypeAlias = JbMaterialImporterABC[JbMaterial]
JbSettingsBase: TypeAlias = JbSettingsABC[JbContainer]
JbAssetImporterBase: TypeAlias = JbAssetImporterABC[JbContainer, JbObject, JbMaterial]
JbAssetExporterBase: TypeAlias = JbAssetExporterABC[JbContainer, JbObject, JbMaterial]

# --- jiko_bridge_blend.jb_settings ---

_SOLO_STACK_SIZE = 5


class JB_PG_SoloEntry(bpy.types.PropertyGroup):
    """One entry in the solo history stack (stored per scene)."""

    collections: bpy.props.StringProperty(default='')

    def set_collections(self, collections: list) -> None:
        """Serialize collection names to string."""
        self.collections = ','.join((c.name for c in collections if c))

    def get_collections(self) -> list:
        """Deserialize collection names back to collections."""
        if not self.collections:
            return []
        return [
            col
            for name in self.collections.split(',')
            if (col := bpy.data.collections.get(name)) is not None
        ]


class JB_PG_SceneSettings(bpy.types.PropertyGroup):
    """Per-scene settings stored on bpy.types.Scene."""

    solo_stack: bpy.props.CollectionProperty(type=JB_PG_SoloEntry)
    export_format: bpy.props.EnumProperty(
        name='Export Format',
        items=[('fbx', 'FBX', 'Export as FBX'), ('abc', 'Alembic', 'Export as Alembic')],
        default='fbx',
    )


class JbSettings(JbSettingsBase):
    """Wrapper for accessing Jiko Bridge addon preferences."""

    def __init__(self, context: bpy.types.Context):
        self._context = context

    @property
    def scene_settings(self) -> JB_PG_SceneSettings | None:
        """Scene settings"""
        scene = self._context.scene
        if scene is None:
            return None
        return getattr(scene, 'jb_settings', None)

    def get_export_format(self) -> str:
        s = self.scene_settings
        if s is None:
            return 'fbx'
        return s.export_format

    def load_solo_stack(self) -> list[list]:
        """Load Solo Stack"""
        s = self.scene_settings
        if s is None:
            return []
        return [entry.get_collections() for entry in s.solo_stack if entry.get_collections()]

    def save_solo_selection(self, containers) -> None:
        s = self.scene_settings
        if s is None:
            return
        entries = [entry.get_collections() for entry in s.solo_stack]
        if entries and set(entries[0]) == set(containers):
            return
        entries.insert(0, containers)
        entries = entries[:_SOLO_STACK_SIZE]
        s.solo_stack.clear()
        for entry_collections in entries:
            entry = s.solo_stack.add()
            entry.set_collections(entry_collections)

    def pop_solo_selection(self) -> list:
        s = self.scene_settings
        if s is None or len(s.solo_stack) < 2:
            return []
        entries = [entry.get_collections() for entry in s.solo_stack]
        previous = entries[1]
        s.solo_stack.clear()
        for entry_collections in entries[1:]:
            entry = s.solo_stack.add()
            entry.set_collections(entry_collections)
        return previous


settings_classes = (JB_PG_SoloEntry, JB_PG_SceneSettings)


def register_settings() -> None:
    """Register Settings"""
    for cls in settings_classes:
        bpy.utils.register_class(cls)
    setattr(bpy.types.Scene, 'jb_settings', bpy.props.PointerProperty(type=JB_PG_SceneSettings))


def unregister_settings() -> None:
    """Unregister settings"""
    if hasattr(bpy.types.Scene, 'jb_settings'):
        delattr(bpy.types.Scene, 'jb_settings')
    for cls in reversed(settings_classes):
        bpy.utils.unregister_class(cls)


# --- jiko_bridge_blend.scene.jb_scene_objects ---


class JbSceneObjects(JbSceneBase):
    """Object operations for Scene."""

    @property
    def _outliner(self) -> Optional[tuple[bpy.types.Area, bpy.types.Region]]:
        ctx = self.source
        if not ctx.screen:
            return None
        for area in ctx.screen.areas:
            if area.type == 'OUTLINER':
                for region in area.regions:
                    if region.type == 'WINDOW':
                        return (area, region)
        return None

    def walk(self, root) -> list[JbData]:
        if not root:
            return []
        return list(self._walk(root))

    def _walk(self, root: list[JbData]) -> Generator[JbData, None, None]:
        seen: set[JbData] = set()

        def walk_object(obj: bpy.types.Object):
            if obj in seen:
                return
            seen.add(obj)
            yield obj
            for child in obj.children:
                yield from walk_object(child)

        def walk_collection(collection: bpy.types.Collection):
            if collection in seen:
                return
            seen.add(collection)
            yield collection
            for obj in collection.objects:
                yield from walk_object(obj)
            for child_col in collection.children:
                yield from walk_collection(child_col)

        for item in root:
            if isinstance(item, bpy.types.Object):
                yield from walk_object(item)
            elif isinstance(item, bpy.types.Collection):
                yield from walk_collection(item)
            elif isinstance(item, bpy.types.Material):
                if item not in seen:
                    seen.add(item)
                    yield item

    def get_selection(self) -> list[JbData]:
        ctx = self.source
        data: list[JbData] = []
        outliner = self._outliner
        if outliner:
            area, region = outliner
            with ctx.temp_override(area=area, region=region):
                selected = ctx.selected_ids
                if selected:
                    for item in selected:
                        if isinstance(
                            item, (bpy.types.Object, bpy.types.Collection, bpy.types.Material)
                        ):
                            data.append(item)
        if not data:
            if not (view_layer := ctx.view_layer):
                return []
            if view_layer.objects:
                data = list(view_layer.objects.selected)
            if (
                not data
                and (active_layer := view_layer.active_layer_collection)
                and (collection := active_layer.collection)
            ):
                data = [collection]
        return data

    def get_materials_from_objects(self, objects) -> list[JbMaterial]:
        materials: set[JbMaterial] = set()
        for obj in objects:
            if isinstance(obj, bpy.types.Material):
                materials.add(obj)
                continue
            if not isinstance(obj, bpy.types.Object):
                continue
            if (data := obj.data) is None:
                continue
            materials.update((mat for mat in getattr(data, 'materials', ()) if mat is not None))
        return list(materials)

    def copy_object_transform(self, obj, target_obj) -> None:
        obj.matrix_world = target_obj.matrix_world.copy()

    def remove_object(self, obj) -> None:
        bpy.data.objects.remove(obj, do_unlink=True)

    def get_children(self, obj) -> list[JbObject | JbContainer]:
        if isinstance(obj, bpy.types.Object):
            return list(obj.children)
        if isinstance(obj, bpy.types.Collection):
            return list(obj.objects) + list(obj.children)
        return []

    def get_depth(self, obj) -> int:
        depth = 0
        if isinstance(obj, bpy.types.Object):
            current = obj.parent
        else:
            return depth
        while current:
            depth += 1
            current = current.parent
        return depth

    def merge_duplicates_materials(self, material) -> None:
        pattern = re.compile('^' + re.escape(material.name) + '\\.\\d+$')
        duplicates = [m for m in bpy.data.materials if pattern.match(m.name)]
        for dup in duplicates:
            dup.user_remap(material)
            bpy.data.materials.remove(dup)

    def _find_layer_collection(self, layer_col, collection) -> bpy.types.LayerCollection | None:
        if layer_col.collection == collection:
            return layer_col
        for child in layer_col.children:
            result = self._find_layer_collection(child, collection)
            if result:
                return result
        return None

    def _set_collection_visibility(self, collection, visible: bool) -> None:
        view_layer = self.source.view_layer
        if not view_layer:
            return
        layer_col = self._find_layer_collection(view_layer.layer_collection, collection)
        if layer_col:
            layer_col.hide_viewport = not visible


# --- jiko_bridge_blend.scene.jb_scene_container ---


class JbSceneContainer(JbSceneObjects):
    """Container and asset management: collections, metadata."""

    def get_container(self, asset) -> Optional[JbContainer]:
        root = self.get_or_create_container('Assets')
        name = f'Asset_{asset.pack_name}_{asset.asset_name}'
        for col in root.children:
            if isinstance(col, bpy.types.Collection) and col.name == name:
                return col
        return None

    def get_or_create_container(self, name, parent=None) -> JbContainer:
        ctx = self.source
        col = bpy.data.collections.get(name)
        if not col:
            col = bpy.data.collections.new(name)
            if parent is not None:
                parent.children.link(col)
            else:
                scene = ctx.scene
                if scene:
                    root_col = scene.collection
                    if root_col is not None:
                        root_col.children.link(col)
            col.color_tag = 'COLOR_04'
        return col

    def get_or_create_asset_container(self, asset, file=None) -> tuple[JbContainer, bool]:
        root = self.get_or_create_container('Assets')
        name = f'Asset_{asset.pack_name}_{asset.asset_name}'
        col = self.get_or_create_container(name, parent=root)
        self.set_asset_data(col, asset, file)
        if name not in [c.name for c in root.children]:
            try:
                root.children.link(col)
            except RuntimeError:
                pass
        existed = True
        if len(col.objects) == 0:
            existed = False
        return (col, existed)

    def get_containers_from_objects(self, objects) -> list[JbContainer]:
        containers: set[JbContainer] = set()
        for obj in objects:
            if isinstance(obj, bpy.types.Collection):
                if self.get_asset_data_from_container(obj):
                    containers.add(obj)
        return list(containers)

    def get_containers_from_instances(self, objects) -> list[JbContainer]:
        containers: set[JbContainer] = set()
        for obj in objects:
            if not isinstance(obj, bpy.types.Object):
                continue
            if obj.instance_type != 'COLLECTION':
                continue
            collection = obj.instance_collection
            if collection is None:
                continue
            if self.get_asset_data_from_container(collection):
                containers.add(collection)
        return list(containers)

    def set_asset_data(self, container, asset, file=None) -> None:
        container['jb_pack_name'] = asset.pack_name or ''
        container['jb_asset_name'] = asset.asset_name or ''
        container['jb_asset_type'] = file.asset_type or '' if file else ''
        container['jb_vault_name'] = asset.vault_name or ''

    def get_asset_data_from_container(self, container) -> Optional[AssetModel]:
        pack_name = container.get('jb_pack_name', None)
        asset_name = container.get('jb_asset_name', None)
        asset_type = container.get('jb_asset_type', None)
        vault_name = container.get('jb_vault_name', None)
        if not (pack_name and asset_name):
            return None
        return AssetModel(
            pack_name=pack_name,
            asset_name=asset_name,
            active_type=asset_type,
            vault_name=vault_name,
        )

    def copy_asset_data(self, src, dst) -> None:
        for key in ('jb_pack_name', 'jb_asset_name', 'jb_asset_type', 'jb_vault_name'):
            if key in src:
                dst[key] = src[key]

    def clear_container(self, container) -> None:
        for obj in list(container.objects):
            container.objects.unlink(obj)
            bpy.data.objects.remove(obj, do_unlink=True)

    def cleanup_container(self, container) -> None:
        for obj in list(container.objects):
            if obj.type == 'EMPTY' and obj.instance_type != 'COLLECTION' and (not obj.children):
                bpy.data.objects.remove(obj, do_unlink=True)
        for child in container.children:
            self.cleanup_container(child)

    def move_objects_to_container(self, objects, container) -> None:
        moved = set()
        objects = self.walk(objects)
        for obj in objects:
            if isinstance(obj, bpy.types.Object):
                if obj in moved:
                    continue
                moved.add(obj)
                for col in list(obj.users_collection):
                    col.objects.unlink(obj)
                if container not in obj.users_collection:
                    container.objects.link(obj)


# --- jiko_bridge_blend.scene.jb_scene_instance ---


class JbSceneInstance(JbSceneContainer):
    """Instance and placeholder management for Blender."""

    def create_instance(self, container, name) -> 'JbObject':
        empty = bpy.data.objects.new(f'Instance_{name}', None)
        empty.instance_type = 'COLLECTION'
        empty.instance_collection = container
        empty['jb_pack_name'] = container.get('jb_pack_name', '')
        empty['jb_asset_name'] = container.get('jb_asset_name', '')
        empty['jb_asset_type'] = container.get('jb_asset_type', '')
        empty['jb_vault_name'] = container.get('jb_vault_name', '')
        scene = self.source.scene
        if scene is not None and scene.collection is not None:
            scene.collection.objects.link(empty)
        return empty

    def create_placeholder(self, asset_model, transform, source) -> 'JbObject':
        pack_name = asset_model.pack_name
        asset_name = asset_model.asset_name
        name = f'{pack_name}__{asset_name}'
        mesh = bpy.data.meshes.new(name)
        bm = bmesh.new()
        bmesh.ops.create_grid(bm, x_segments=1, y_segments=1, size=0.5)
        bm.to_mesh(mesh)
        bm.free()
        obj = bpy.data.objects.new(name, mesh)
        obj['jb_placeholder_pack'] = pack_name
        obj['jb_placeholder_asset'] = asset_name
        obj.matrix_world = transform
        col = source.collection
        mat = bpy.data.materials.get(name) or bpy.data.materials.new(name)
        mesh.materials.append(mat)
        if col is not None:
            col.objects.link(obj)
        return obj

    def get_names_from_placeholder(self, obj) -> 'List[str]':
        names = set()
        if (
            not isinstance(obj, bpy.types.Object)
            or obj.data is None
            or (not isinstance(obj.data, bpy.types.Mesh))
            or (not hasattr(obj.data, 'materials'))
            or (len(obj.data.vertices) != 4)
        ):
            return []
        mat_name = next((m.name for m in obj.data.materials if m), None)
        if mat_name:
            names.add(mat_name)
        return list(names)

    def replace_instances_with_placeholders(self, objects, source) -> 'list[JbObject]':
        result = []
        for obj in objects:
            if obj.instance_type == 'COLLECTION' and obj.instance_collection:
                asset_model = self.get_asset_data_from_container(obj.instance_collection)
                if asset_model:
                    placeholder = self.create_placeholder(
                        asset_model, obj.matrix_world.copy(), source
                    )
                    self.remove_object(obj)
                    result.append(placeholder)
                    continue
            result.append(obj)
        return result


# --- jiko_bridge_blend.scene.jb_scene_file ---


class JbSceneFile(JbSceneInstance):
    """File import/export layer in the scene hierarchy."""

    def __init__(self):
        self.cache_path = os.path.join(tempfile.gettempdir(), 'jiko-bridge')
        os.makedirs(self.cache_path, exist_ok=True)

    def get_temp_path(self, ext: str) -> str:
        """Generate a unique temporary file path with the given extension."""
        filename = f'tmp_{uuid.uuid4().hex}.{ext}'
        return os.path.join(self.cache_path, filename)

    def import_file(self, file_path) -> bool:
        if not os.path.exists(file_path):
            self.logger.error('Import file not found: %s', file_path)
            return False
        ext = Path(file_path).suffix.lower().lstrip('.')
        handler = {
            'fbx': self._import_fbx,
            'abc': self._import_alembic,
            'obj': self._import_obj,
            'usd': self._import_usd,
            'usda': self._import_usd,
            'usdc': self._import_usd,
            'glb': self._import_gltf,
            'gltf': self._import_gltf,
        }.get(ext)
        if not handler:
            self.logger.error('Unsupported file extension: %s', ext)
            return False
        return handler(file_path)

    def _import_fbx(self, file_path) -> bool:
        self.logger.debug('Importing FBX asset: %s', file_path)
        try:
            bpy.ops.import_scene.fbx(
                filepath=file_path, use_image_search=False, automatic_bone_orientation=True
            )
        except Exception as e:
            self.logger.error('FBX import failed: %s', e)
            return False
        return True

    def _import_alembic(self, file_path: str) -> bool:
        try:
            bpy.ops.wm.alembic_import(filepath=file_path, as_background_job=False)
        except Exception as e:
            self.logger.error('Alembic import failed: %s', e)
            return False
        return True

    def _import_obj(self, file_path: str) -> bool:
        try:
            bpy.ops.wm.obj_import(filepath=file_path)
        except Exception as e:
            self.logger.error('OBJ import failed: %s', e)
            return False
        return True

    def _import_usd(self, file_path: str) -> bool:
        try:
            bpy.ops.wm.usd_import(filepath=file_path)
        except Exception as e:
            self.logger.error('USD import failed: %s', e)
            return False
        return True

    def _import_gltf(self, file_path: str) -> bool:
        try:
            bpy.ops.import_scene.gltf(filepath=file_path)
        except Exception as e:
            self.logger.error('GLTF import failed: %s', e)
            return False
        return True

    def export_file(self, ext) -> Optional[str]:
        """Exports the current Blender scene to a file."""
        file_path = self.get_temp_path(ext)
        handler = {
            'fbx': self._export_fbx,
            'abc': self._export_alembic,
            'glb': self._export_gltf,
            'obj': self._export_obj,
            'usd': self._export_usd,
        }.get(ext)
        if not handler:
            self.logger.error('Unsupported export extension: %s', ext)
            return None
        return handler(file_path)

    def _export_fbx(self, file_path) -> Optional[str]:
        try:
            bpy.ops.export_scene.fbx(
                filepath=file_path,
                use_selection=False,
                apply_scale_options='FBX_SCALE_UNITS',
                global_scale=1,
                path_mode='COPY',
                embed_textures=False,
                bake_space_transform=False,
                axis_up='Y',
                axis_forward='-Z',
            )
            self.logger.info('FBX exported: %s', file_path)
            return file_path
        except Exception as e:
            self.logger.error('FBX export failed: %s', e)
            return None

    def _export_alembic(self, file_path: str) -> Optional[str]:
        try:
            bpy.ops.wm.alembic_export(filepath=file_path, selected=False, face_sets=True)
            self.logger.info('Alembic exported: %s', file_path)
            return file_path
        except Exception as e:
            self.logger.error('Alembic export failed: %s', e)
            return None

    def _export_gltf(self, file_path: str) -> Optional[str]:
        try:
            bpy.ops.export_scene.gltf(filepath=file_path, use_selection=False, export_format='GLB')
            self.logger.info('GLTF exported: %s', file_path)
            return file_path
        except Exception as e:
            self.logger.error('GLTF export failed: %s', e)
            return None

    def _export_obj(self, _file_path: str):
        self.logger.warning('OBJ export not implemented yet')

    def _export_usd(self, _file_path: str):
        self.logger.warning('USD export not implemented yet')


# --- jiko_bridge_blend.scene.jb_scene_temp ---


class JBSceneTemp(JbSceneFile):
    """Scene-level operations: temporary scene contexts."""

    @contextmanager
    def temp_source(self, objects=None, unit_scale=1.0, debug=False):
        temp = bpy.data.scenes.new('_jb_temp_scene')
        if not isinstance(temp, bpy.types.Scene):
            raise TypeError('temp must be a Scene')
        settings = temp.unit_settings
        if settings is not None:
            settings.system = 'METRIC'
            settings.scale_length = unit_scale
        try:
            with self.source.temp_override(scene=temp):
                col = temp.collection
                if objects is not None and col is not None:
                    self._copy_source(objects, col)
                yield temp
        finally:
            if not debug:
                try:
                    if temp.name in bpy.data.scenes:
                        bpy.data.scenes.remove(temp, do_unlink=True)
                        bpy.data.orphans_purge(do_recursive=True)
                except RuntimeError:
                    pass

    @contextmanager
    def _view3d_context(self, scene):
        """Provides a valid VIEW_3D context override required by certain bpy operators."""
        ctx = self.source
        wm = getattr(ctx, 'window_manager', None)
        if not wm or not wm.windows:
            raise RuntimeError('No active window manager or windows found')
        window = wm.windows[0]
        window.scene = scene
        screen = window.screen
        if not screen or not screen.areas:
            raise RuntimeError('Active window has no screens or areas configured')
        area = next((a for a in screen.areas if a.type == 'VIEW_3D'), screen.areas[0])
        region = next((r for r in area.regions if r.type == 'WINDOW'), None)
        with ctx.temp_override(window=window, area=area, region=region):
            print('after', bpy.context.scene)
            yield

    def _copy_source(self, src: list[JbData], dst: JbContainer) -> None:
        orig_to_new: dict[bpy.types.Object, bpy.types.Object] = {}
        objects = self.walk(src)
        if not objects:
            self.logger.warning('No objects found in source')
            return
        for obj in sorted(objects, key=self.get_depth):
            if isinstance(obj, bpy.types.Collection):
                continue
            if isinstance(obj, bpy.types.Object):
                new_obj = obj.copy()
                dst.objects.link(new_obj)
                if obj.parent and obj.parent in orig_to_new:
                    new_obj.parent = orig_to_new[obj.parent]
                    new_obj.parent_type = obj.parent_type
                    new_obj.parent_bone = obj.parent_bone
                    new_obj.matrix_parent_inverse = obj.matrix_parent_inverse.copy()
                orig_to_new[obj] = new_obj


# --- jiko_bridge_blend.scene.jb_scene ---


class JbScene(JBSceneTemp):
    """High-level operations for the active Blender scene."""

    def __init__(self, source):
        super().__init__()
        self._logger = get_logger('jiko_bridge_blend.scene.jb_scene')
        self._source = source

    @property
    def logger(self) -> Logger:
        return self._logger

    @property
    def source(self) -> JbSource:
        if self._source is not None:
            return self._source
        return bpy.context

    def import_with_temp(self, file_path, target) -> None:
        with self.temp_source(debug=False) as temp:
            with self._view3d_context(temp):
                if not self.import_file(file_path):
                    self.logger.warning('No objects imported for file: %s', file_path)
                    return
            self._copy_source([temp.collection], target)

    def export_with_temp(self, src, ext) -> Optional[str]:
        with self.temp_source(src, debug=False) as temp:
            col = temp.collection
            if not col or not col.objects:
                self.logger.warning('No objects to export.')
                return None
            copies = list(col.objects)
            self.replace_instances_with_placeholders(copies, temp)
            with self._view3d_context(temp):
                return self.export_file(ext)

    def get_project_filepath(self) -> Optional[str]:
        """Get the current Blender project file path."""
        filepath = bpy.data.filepath
        if not filepath:
            self.logger.warning('Current Blender project is not saved.')
            return None
        return filepath

    def solo(self):
        objects = self.get_selection()
        instances = self.get_containers_from_instances(objects)
        containers = self.get_containers_from_objects(objects)
        combine = instances + containers
        settings = JbSettings(self.source)
        if not combine:
            combine = settings.pop_solo_selection()
        else:
            settings.save_solo_selection(combine)
        if not combine:
            return
        root = self.get_or_create_container('Assets')
        self._set_collection_visibility(root, True)
        for child in root.children:
            self._set_collection_visibility(child, False)
        for col in combine:
            self._set_collection_visibility(col, True)
        bpy.ops.view3d.view_all()


# --- jiko_bridge_blend.jb_asset_exporter ---

asset_export_logger = get_logger('jiko_bridge_blend.jb_asset_exporter')


class JbAssetExporter(JbAssetExporterBase):
    """Export asset class"""

    def __init__(self, source: JbSource):
        self.source = source
        self.api = JbAPI()
        self.scene = JbScene(source)

    def export_asset(self) -> None:
        """Export the selected asset or create a new one."""
        selected_objects, asset_containers = self._collect_data()
        if asset_containers:
            for container in asset_containers:
                self._update_asset(container)
        elif selected_objects:
            self._create_new_asset(selected_objects)
        else:
            self._export_project()

    def export_message(self) -> str:
        selected_objects, asset_containers = self._collect_data()
        if asset_containers:
            return f'Update existing assets?\n{len(asset_containers)} asset(s) will be updated'
        if selected_objects:
            return f'No asset containers found in selection. Create new asset with {len(selected_objects)} object(s)?'
        return 'Export project.'

    def _collect_data(self):
        selected_objects = self.scene.get_selection()
        asset_containers = self.scene.get_containers_from_objects(selected_objects)
        return (selected_objects, asset_containers)

    def _update_asset(self, container) -> None:
        asset_model = self.scene.get_asset_data_from_container(container)
        if not asset_model:
            asset_export_logger.error('Invalid asset information')
            return
        asset = self.api.get_asset(asset_model)
        if not asset or not asset.files or (not asset.pack_name) or (not asset.asset_name):
            asset_export_logger.error("Failed to fetch asset '%s'.", asset_model.asset_name)
            return
        file = next(iter(asset.files))
        if not file.filepath:
            asset_export_logger.error(
                "Filepath missing for asset '%s'. Cannot export.", asset_model.asset_name
            )
            return
        ext = Path(file.filepath.lower()).suffix.lstrip('.')
        if not ext:
            asset_export_logger.error(
                "Unable to determine export extension from filepath '%s' for '%s'.",
                file.filepath,
                asset_model.asset_name,
            )
            return
        objects = self.scene.get_children(container)
        if not objects:
            asset_export_logger.error(
                "No objects found in container for asset '%s'. Cannot export.",
                asset_model.asset_name,
            )
            return
        filepath = self.scene.export_with_temp(objects, ext)
        if not filepath:
            return
        asset.files = [
            AssetFile(filepath=filepath, asset_type=file.asset_type, bridge_type=file.bridge_type)
        ]
        self.api.update_asset(asset)

    def _create_new_asset(self, objects) -> None:
        fmt = JbSettings(self.source).get_export_format()
        filepath = self.scene.export_with_temp(objects, fmt)
        if not filepath:
            asset_export_logger.error('Export failed.')
            return
        asset = self.api.create_asset(AssetModel(files=[AssetFile(filepath=filepath)]))
        if not asset or not asset.files:
            asset_export_logger.error("No asset found for filepath '%s'", filepath)
            return
        for file in asset.files:
            container, _ = self.scene.get_or_create_asset_container(asset, file)
            self.scene.move_objects_to_container(objects, container)
            asset_export_logger.info(
                "Asset '%s' created with type '%s'.", asset.asset_name, file.asset_type
            )

    def _export_project(self) -> None:
        if filepath := self.scene.get_project_filepath():
            self.api.create_asset(AssetModel(files=[AssetFile(filepath=filepath)]))


# --- jiko_bridge_blend.materials.jb_base_node_material ---

COL_WIDTH = 300
ROW_HEIGHT = 320


class JBBaseNodeMaterial:
    """Base node material for Blender node graphs."""

    def __init__(self, material: 'bpy.types.Material'):
        self._mat = material

    @property
    def _nodes(self):
        return self._mat.node_tree.nodes

    @property
    def _links(self):
        return self._mat.node_tree.links

    def _wire_channel(self, channel: 'str', path: 'str') -> 'None':
        method = getattr(self, f'_wire_{channel}', None)
        if method is not None:
            method(path)

    def apply_channel(self, channel: 'str', path: 'str') -> 'None':
        """Apply a texture channel to the material."""
        self._wire_channel(channel, path)
        self.clear_orphans()
        self.auto_layout()

    def clear_orphans(self) -> 'None':
        """Remove nodes with no connected inputs or outputs."""
        to_remove = [
            node
            for node in self._nodes
            if not any((s.is_linked for s in node.inputs))
            and (not any((s.is_linked for s in node.outputs)))
        ]
        for node in to_remove:
            self._nodes.remove(node)

    def auto_layout(self) -> 'None':
        """Automatically arranges nodes from left to right based on depth in the graph."""
        if self._mat is None:
            return
        nodes = self._nodes

        def get_depth(node, visited=None):
            if visited is None:
                visited = set()
            if node.name in visited:
                return 0
            visited.add(node.name)
            input_nodes = [link.from_node for socket in node.inputs for link in socket.links]
            if not input_nodes:
                return 0
            return 1 + max((get_depth(n, visited) for n in input_nodes))

        columns: 'dict[int, list[bpy.types.Node]]' = defaultdict(list)
        for node in nodes:
            depth = get_depth(node)
            columns[depth].append(node)
        max_depth = max(columns.keys(), default=0)
        for depth, col_nodes in columns.items():
            x = (depth - max_depth) * COL_WIDTH
            for row, node in enumerate(col_nodes):
                y = -row * ROW_HEIGHT
                node.location = (x, y)


# --- jiko_bridge_blend.materials.jb_standard_material ---

standard_material_logger = get_logger('jiko_bridge_blend.materials.jb_standard_material')
NODE_OUTPUT = 'ShaderNodeOutputMaterial'
NODE_OUTPUT_NAME = 'Material Output'
NODE_BSDF = 'ShaderNodeBsdfPrincipled'
NODE_BSDF_NAME = 'Principled BSDF'
NODE_TEX_IMAGE = 'ShaderNodeTexImage'


class JBStandardMaterial(JBBaseNodeMaterial):
    """Principled BSDF node material for Blender."""

    @property
    def _nodes(self):
        return self._mat.node_tree.nodes

    @property
    def _links(self):
        return self._mat.node_tree.links

    @property
    def _output(self):
        output = self._nodes.get(NODE_OUTPUT_NAME)
        if output is None:
            output = self._nodes.new(NODE_OUTPUT)
            output.name = NODE_OUTPUT_NAME
            output.location = (600, 0)
        return output

    @property
    def _bsdf(self):
        bsdf = self._nodes.get(NODE_BSDF_NAME)
        if bsdf is None:
            bsdf = self._nodes.new(NODE_BSDF)
            self._links.new(bsdf.outputs['BSDF'], self._output.inputs['Surface'])
            bsdf.location = (300, 0)
        return bsdf

    def _make_texture_node(
        self, channel: str, path: str, color_space: str = 'sRGB'
    ) -> bpy.types.Node:
        """Find existing texture node for channel or create a new one."""
        node = self._nodes.get(channel)
        if node is None:
            node = self._nodes.new(NODE_TEX_IMAGE)
            node.name = channel
        try:
            img = bpy.data.images.load(path, check_existing=True)
            if color_space != 'sRGB':
                img.colorspace_settings.name = 'Non-Color'
            node.image = img
        except RuntimeError as e:
            standard_material_logger.warning("Failed to load texture '%s': %s", path, e)
        return node

    def _wire_basecolor(self, path: str) -> None:
        tex = self._make_texture_node('basecolor', path, 'sRGB')
        self._links.new(tex.outputs['Color'], self._bsdf.inputs['Base Color'])

    def _wire_metallic(self, path: str) -> None:
        tex = self._make_texture_node('metallic', path, 'Non-Color')
        self._links.new(tex.outputs['Color'], self._bsdf.inputs['Metallic'])

    def _wire_roughness(self, path: str) -> None:
        tex = self._make_texture_node('roughness', path, 'Non-Color')
        self._links.new(tex.outputs['Color'], self._bsdf.inputs['Roughness'])

    def _wire_normal(self, path: str) -> None:
        tex = self._make_texture_node('normal', path, 'Non-Color')
        normal_map = self._nodes.get('normal_map')
        if normal_map is None:
            normal_map = self._nodes.new('ShaderNodeNormalMap')
            normal_map.name = 'normal_map'
        self._links.new(tex.outputs['Color'], normal_map.inputs['Color'])
        self._links.new(normal_map.outputs['Normal'], self._bsdf.inputs['Normal'])

    def _wire_emissive(self, path: str) -> None:
        tex = self._make_texture_node('emissive', path, 'sRGB')
        self._links.new(tex.outputs['Color'], self._bsdf.inputs['Emission Color'])
        self._bsdf.inputs['Emission Strength'].default_value = 1.0

    def _wire_opacity(self, path: str) -> None:
        tex = self._make_texture_node('opacity', path, 'Non-Color')
        self._links.new(tex.outputs['Color'], self._bsdf.inputs['Alpha'])
        self._mat.blend_method = 'HASHED'

    def _wire_height(self, path: str) -> None:
        tex = self._make_texture_node('height', path, 'Non-Color')
        disp_node = self._nodes.get('displacement')
        if disp_node is None:
            disp_node = self._nodes.new('ShaderNodeDisplacement')
            disp_node.name = 'displacement'
        self._links.new(tex.outputs['Color'], disp_node.inputs['Height'])
        self._links.new(disp_node.outputs['Displacement'], self._output.inputs['Displacement'])

    def _wire_ao(self, path: str) -> None:
        ao_tex = self._make_texture_node('ao', path, 'Non-Color')
        base_tex = self._nodes.get('basecolor')
        if base_tex is None:
            return
        mix = self._nodes.get('ao_mix')
        if mix is None:
            mix = self._nodes.new('ShaderNodeMixRGB')
            mix.name = 'ao_mix'
        mix.blend_type = 'MULTIPLY'
        mix.inputs['Fac'].default_value = 1.0
        self._links.new(base_tex.outputs['Color'], mix.inputs['Color1'])
        self._links.new(ao_tex.outputs['Color'], mix.inputs['Color2'])
        self._links.new(mix.outputs['Color'], self._bsdf.inputs['Base Color'])


# --- jiko_bridge_blend.materials.jb_material_importer ---

material_import_logger = get_logger('jiko_bridge_blend.materials.jb_material_importer')


class JbMaterialImporter(JbMaterialImporterBase):
    """Material importer that handles Blender materials."""

    def __init__(self, source):
        self.source = source

    def get_material_name(self, material):
        return material.name if material else None

    def set_material_name(self, material, name):
        if material:
            material.name = name

    def import_material(self, asset: AssetModel, file: AssetFile) -> Optional[bpy.types.Material]:
        """Import a single material file into the scene."""
        if file.asset_type is None or file.filepath is None:
            material_import_logger.error('Material file is missing type or path')
            return None
        channel = file.asset_type.lower()
        path = file.filepath
        material_name = f'{asset.pack_name}__{asset.asset_name}'
        material = bpy.data.materials.get(material_name)
        if not material:
            material = bpy.data.materials.new(name=material_name)
        if material is None:
            material_import_logger.error('Failed to create material: %s', material_name)
            return None
        standard = JBStandardMaterial(material)
        standard.apply_channel(channel, path)
        return material


# --- jiko_bridge_blend.jb_asset_importer ---

asset_import_logger = get_logger('jiko_bridge_blend.jb_asset_importer')


class JbAssetImporter(JbAssetImporterBase):
    """Handles importing assets from Jiko Bridge into scene."""

    def __init__(self, source: JbSource):
        self.api = JbAPI()
        self.scene = JbScene(source)
        self.materials = JbMaterialImporter(source)
        self._asset_cache: dict[str, AssetModel | None] = {}

    def import_assets(self):
        self._asset_cache = {}
        assets = self._collect_assets()
        for asset in assets:
            self._import_single(asset)

    def import_message(self) -> str:
        materials, containers = self._collect_data()
        if materials:
            return f'Import assets for materials?\n{len(materials)} material(s) with asset info found in selection.'
        if containers:
            return f'Import assets for asset containers?\n{len(containers)} asset container(s) found in selection.'
        return 'Import active asset from Jiko Bridge.'

    def _collect_data(self) -> tuple[list[JbMaterial], list[JbContainer]]:
        objects = self.scene.get_selection()
        materials = self.scene.get_materials_from_objects(objects)
        containers = self.scene.get_containers_from_objects(objects)
        return (materials, containers)

    def _collect_assets(self) -> list[AssetModel]:
        assets: list[AssetModel] = []
        materials, containers = self._collect_data()
        if materials:
            for mat in materials:
                mat_name = self.materials.get_material_name(mat)
                asset_model = AssetModel.from_string(mat_name)
                asset = self._resolve_asset(mat_name)
                if not asset:
                    continue
                assets.append(asset)
                if not asset_model:
                    self.materials.set_material_name(mat, f'{asset.pack_name}__{asset.asset_name}')
        elif containers:
            for container in containers:
                self.scene.clear_container(container)
                asset_model = self.scene.get_asset_data_from_container(container)
                if not asset_model:
                    continue
                asset_model.active_type = None
                asset = self.api.get_asset(asset_model)
                if asset:
                    assets.append(asset)
        else:
            asset = self.api.get_active_asset()
            if asset:
                assets.append(asset)
        return list(assets)

    def _resolve_asset(self, name: str) -> AssetModel | None:
        """Resolve an asset by bundled name or by search, caching misses too."""
        if name in self._asset_cache:
            return self._asset_cache[name]
        asset_model = AssetModel.from_string(name)
        if asset_model:
            asset = self.api.get_asset(asset_model)
        else:
            asset = self.api.get_asset_by_search(name)
        self._asset_cache[name] = asset
        return asset

    def _import_single(self, asset: AssetModel) -> None:
        for file in asset.files:
            match file.bridge_type:
                case 'model':
                    container = self._create_model(asset, file)
                    self._convert_to_instances(container)
                case 'material':
                    mat = self.materials.import_material(asset, file)
                    if mat:
                        self.scene.merge_duplicates_materials(mat)
                case _:
                    asset_import_logger.warning('Unsupported bridge type: %s', file.bridge_type)

    def _create_model(self, asset, file):
        container, exists = self.scene.get_or_create_asset_container(asset, file)
        if exists:
            self.scene.create_instance(container, asset.asset_name)
        else:
            self.scene.import_with_temp(file.filepath, container)
        return container

    def _convert_to_instances(self, container) -> None:
        queue = [container]
        visited = set()
        while queue:
            current = queue.pop(0)
            if id(current) in visited:
                continue
            visited.add(id(current))
            objects = self.scene.walk([current])
            for obj in objects:
                asset_model = None
                for name in self.scene.get_names_from_placeholder(obj):
                    asset_model = self._resolve_asset(name)
                    if asset_model:
                        break
                if not asset_model:
                    continue
                asset_container = self._resolve_placeholder(obj, current, asset_model)
                if asset_container:
                    queue.append(asset_container)
            self.scene.cleanup_container(current)

    def _resolve_placeholder(self, obj, container, asset_model) -> JbContainer | None:
        asset_container = self.scene.get_container(asset_model)
        new_container = None
        if not asset_container:
            for file in asset_model.files:
                asset_container, exists = self.scene.get_or_create_asset_container(
                    asset_model, file
                )
                if not exists:
                    self.scene.import_with_temp(file.filepath, asset_container)
            new_container = asset_container
        instance = self.scene.create_instance(asset_container, asset_model.asset_name)
        self.scene.copy_object_transform(instance, obj)
        self.scene.move_objects_to_container([instance], container)
        self.scene.remove_object(obj)
        return new_container


# --- jiko_bridge_blend.jb_commands ---


class JB_PT_Commands(bpy.types.Panel):
    """Main panel for Jiko Bridge commands."""

    bl_label = 'Jiko Bridge'
    bl_idname = 'JB_PT_MAIN'
    bl_space_type = 'VIEW_3D'
    bl_region_type = 'UI'
    bl_category = 'Jiko Bridge'

    def draw(self, context: bpy.types.Context):
        layout = self.layout
        if not layout:
            return
        col = layout.column(align=True)
        col.operator('jiko_bridge.import_asset', text='Import Asset', icon='IMPORT')
        col.operator('jiko_bridge.export_asset', text='Export Asset', icon='EXPORT')
        col.operator('jiko_bridge.solo', text='Solo Asset', icon='ZOOM_SELECTED')
        col.separator()
        settings = JbSettings(context).scene_settings
        if settings is not None:
            box = col.box()
            box.label(text='Settings', icon='PREFERENCES')
            box.prop(settings, 'export_format', text='Export Format')


class JB_MT_PIE_AssetActions(bpy.types.Menu):
    """Circular pie menu for asset import/export."""

    bl_idname = 'JB_MT_PIE_MAIN'
    bl_label = 'Jiko Bridge'

    def draw(self, _context: bpy.types.Context):
        layout = self.layout
        if not layout:
            return
        pie = layout.menu_pie()
        pie.operator('jiko_bridge.import_asset', text='Import Asset', icon='IMPORT')
        pie.operator('jiko_bridge.export_asset', text='Export Asset', icon='EXPORT')
        pie.operator('jiko_bridge.solo', text='Solo Asset', icon='ZOOM_SELECTED')


# --- jiko_bridge_blend.jb_utils ---

addon_keymaps: list = []


def register_keymap():
    """Register keymap"""
    wm = bpy.context.window_manager
    if not wm:
        return
    kc = wm.keyconfigs.addon
    if kc:
        km = kc.keymaps.get('3D View')
        if km is None:
            km = kc.keymaps.new(name='3D View', space_type='VIEW_3D')
        for item in km.keymap_items:
            if (
                item.idname == 'wm.call_menu_pie'
                and item.properties.get('name', '') == 'JB_MT_PIE_MAIN'
            ):
                return
        kmi = km.keymap_items.new('wm.call_menu_pie', type='J', value='PRESS', shift=True)
        kmi.properties.name = 'JB_MT_PIE_MAIN'
        addon_keymaps.append((km, kmi))


def unregister_keymap():
    """Unregister keymap"""
    for km, kmi in addon_keymaps:
        km.keymap_items.remove(kmi)
    addon_keymaps.clear()


# --- jiko_bridge_blend.jb_plugin ---


class JB_OT_AssetImport(bpy.types.Operator):
    """Import asset from Jiko Bridge."""

    bl_idname = 'jiko_bridge.import_asset'
    bl_label = 'Import Asset'
    bl_description = 'Import active asset from Jiko Bridge'
    bl_options = {'REGISTER', 'UNDO'}

    def invoke(self, context, event):
        importer = JbAssetImporter(context)
        msg = importer.import_message()
        return context.window_manager.invoke_confirm(self, event, message=msg)

    def execute(self, context):
        importer = JbAssetImporter(context)
        importer.import_assets()
        return {'FINISHED'}


class JB_OT_AssetExport(bpy.types.Operator):
    """Export asset to Jiko Bridge."""

    bl_idname = 'jiko_bridge.export_asset'
    bl_label = 'Export Asset'
    bl_description = 'Export selected objects as a new asset or update existing'
    bl_options = {'REGISTER', 'UNDO'}

    def invoke(self, context, event):
        exporter = JbAssetExporter(context)
        msg = exporter.export_message()
        return context.window_manager.invoke_confirm(self, event, message=msg)

    def execute(self, context):
        exporter = JbAssetExporter(context)
        exporter.export_asset()
        return {'FINISHED'}


class JB_OT_Solo(bpy.types.Operator):
    """Solo selected asset."""

    bl_idname = 'jiko_bridge.solo'
    bl_label = 'Solo Asset'
    bl_description = 'Isolate selected asset collections'
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        JbScene(context).solo()
        return {'FINISHED'}


operator_classes = [
    JB_PT_Commands,
    JB_OT_Solo,
    JB_OT_AssetExport,
    JB_OT_AssetImport,
    JB_MT_PIE_AssetActions,
]


def register():
    """Register addon classes."""
    for cls in operator_classes:
        bpy.utils.register_class(cls)
    register_keymap()
    register_settings()


def unregister():
    """Unregister addon classes."""
    for cls in reversed(operator_classes):
        bpy.utils.unregister_class(cls)
    unregister_keymap()
    unregister_settings()


# --- jiko_bridge_blend.materials ---


# --- jiko_bridge_blend.scene ---


# --- entry.py ---

__all__ = ['bl_info', 'register', 'unregister']
bl_info = {
    'name': 'Jiko Bridge',
    'author': 'JIKO',
    'version': (1, 0),
    'blender': (5, 0, 1),
    'location': 'View3D > Sidebar > Jiko Bridge',
    'description': 'Jiko Bridge',
    'category': '3D View',
    'doc_url': 'https://with-jiko.com',
    'tracker_url': 'https://t.me/withjiko',
}
if __name__ == '__main__':
    register()
